- README.md
- docs/antora.yml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/agent-and-tools.adoc
- docs/modules/ROOT/pages/ai-services.adoc
- docs/modules/ROOT/pages/chroma-store.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/llms.adoc
- docs/modules/ROOT/pages/openai.adoc
- docs/modules/ROOT/pages/prompt-engineering.adoc
- docs/modules/ROOT/pages/redis-store.adoc
- docs/modules/ROOT/pages/retrievers.adoc
- integration-tests/hugging-face/pom.xml
- integration-tests/ollama/pom.xml
- integration-tests/openai/pom.xml
Hey there,
I wanted to know what you were up to and went through the (amazing!) documentation to understand things better. I fixed a few very minor things along the way.
- [Make sure ITs dependencies are properly constrained](https://github.com/quarkiverse/quarkus-langchain4j/commit/ee88f876f1e999a4afc7ad8ddf081fb5d0e60af5)
- [Minor adjustments to the documentation](https://github.com/quarkiverse/quarkus-langchain4j/commit/b5fcec2cbe1f6d0209118d8cbd1aa3efb6cf1d3e) 
- Avoid Quarkus prefix and double extension name in UI (this was discussed with Holly a long time ago but I fixed it in the template only yesterday)
- Various very minor improvements/fixes
> Various minor things

- .github/project.yml
Try again as the previous attempt failed
> Release 0.1.0

- README.md
Wait for https://github.com/quarkiverse/quarkiverse-docs/pull/125 to be merged and the website to be generated.
> Point to generated documentation

- docs/modules/ROOT/pages/includes/attributes.adoc
The release workflow wasn't able to push it.
> Update version in documentation

- docs/modules/ROOT/pages/openai.adoc
> Add documentation about using OpenAiRestApi manually

- docs/modules/ROOT/pages/agent-and-tools.adoc
> Add explanation of tools in docs

- chroma/deployment/src/main/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaProcessor.java
- core/deployment/pom.xml
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/EmbeddingModelBuildItem.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/EmbeddingStoreBuildItem.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/InProcessEmbeddingProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolsMetadataBuildItem.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/AiServiceInfo.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/Langchain4jDevUIProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/ToolMethodInfo.java
- core/deployment/src/main/resources/dev-ui/qwc-aiservices.js
- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
- core/deployment/src/main/resources/dev-ui/qwc-tools.js
- core/runtime/pom.xml
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/EmbeddingStoreJsonRPCService.java
- docs/modules/ROOT/pages/index.adoc
- integration-tests/devui/pom.xml
- integration-tests/devui/src/test/java/devui/Langchain4jDevUIJsonRpcTest.java
- integration-tests/pom.xml
- pinecone/deployment/src/main/java/io/quarkiverse/langchain4j/pinecone/PineconeProcessor.java
- redis/deployment/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStoreProcessor.java
Fixes #78
Features:
- View information about declarative AI services and tools
- Add embeddings into the store, if it exists in the CDI container
- Search for relevant embeddings and view them as a table
The 'embedding store' page is currently only enabled if there is exactly one EmbeddingStore and one EmbeddingModel in the CDI container
> Dev UI for Langchain4j

- core/deployment/src/main/resources/dev-ui/qwc-aiservices.js
- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
- core/deployment/src/main/resources/dev-ui/qwc-tools.js
As per review, cleaned some unused imports and classes etc in the dev ui code
> clean up dev ui code

- samples/chatbot/pom.xml
- samples/csv-chatbot/pom.xml
mvnpm should be explicit choice. i.e. mvn -Pmvnpm otherwise every request to a new artifact takes unnecessary time.
> mvnpm should be explicit choice. i.e. mvn -Pmvnpm otherwise every request to a new artifact takes unnecessary time.

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- openai/openai-vanilla/deployment/pom.xml
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
> Ignore OpenTelemetry parameter annotations

- core/runtime/src/main/java/io/quarkiverse/langchain4j/ChatMemoryRemover.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/CustomChatMemoryStoreTest.java
> Make @ApplicationScoped beans work with ChatMemoryRemover

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/Langchain4jDotNames.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContextQualifier.java
- integration-tests/openai/pom.xml
- integration-tests/openai/src/main/java/org/acme/example/openai/aiservices/AssistantResourceWithFallback.java
- integration-tests/openai/src/test/java/org/acme/example/openai/aiservices/AssistantResourceWithFallbackTest.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
> Properly support Smallrye Fault Tolerance

- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/Langchain4jAzureOpenAiConfig.java
> In azure openai extension, need a way to override the base url

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/MetricsCountedWrapper.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/MetricsTimedWrapper.java
- docs/modules/ROOT/pages/ai-services.adoc
- integration-tests/openai/src/main/java/org/acme/example/openai/aiservices/AssistantResourceWithMetrics.java
- integration-tests/openai/src/test/java/org/acme/example/openai/aiservices/AssistantResourceWithMetricsTest.java
> Add counted metrics

- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
Otherwise, if it takes a long time, it might look like nothing is happening..
> Add a 'Working' text while waiting for results in Dev UI

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/EmbeddingModelBuildItem.java
- openai/openai-vanilla/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/OpenAiProcessor.java
... when an OpenAi model is used for embedding
> Fix missing EmbeddingStore Dev UI page

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/ToolExecutorTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/tool/QuarkusToolExecutor.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/ToolValidationTest.java
> Support no-args tools

- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ToolCallBuilderMixin.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ToolCallMixin.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ToolTypeDeserializer.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ToolTypeMixin.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ToolTypeSerializer.java
> Fix tool call serialization/deserialization issues

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/OptionalUtil.java
- hugging-face/runtime/src/main/java/io/quarkiverse/langchain4j/huggingface/runtime/HuggingFaceRecorder.java
- hugging-face/runtime/src/main/java/io/quarkiverse/langchain4j/huggingface/runtime/config/ChatModelConfig.java
- hugging-face/runtime/src/main/java/io/quarkiverse/langchain4j/huggingface/runtime/config/Langchain4jHuggingFaceConfig.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ChatModelConfig.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/EmbeddingModelConfig.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/Langchain4jAzureOpenAiConfig.java
- openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
- openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ChatModelConfig.java
- openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ImageModelConfig.java
- openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/Langchain4jOpenAiConfig.java
- openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ModerationModelConfig.java
> Allows for specific model config options to override client-wide logging config

- ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/EmbeddingModelBuildConfig.java
- ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/Langchain4jOllamaOpenAiBuildConfig.java
- ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaProcessor.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/EmbeddingRequest.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/EmbeddingResponse.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaClient.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaEmbeddingModel.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/OllamaRecorder.java
Tested on my sample project and worked, you have to set the chat-model because the default is `latest` which feels weird (maybe based on old ollama docs ? ) 
- Relates to: #181
> Add embeddings endpoint support for Ollama

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/dev-ui.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-huggingface.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
- openai/openai-vanilla/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/devui/OpenAiDevUIImagePageProcessor.java
- openai/openai-vanilla/deployment/src/main/resources/dev-ui/qwc-images.js
- openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/devui/OpenAiImagesJsonRPCService.java
> Image model Dev UI page + docs

- core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusAiServicesFactory.java
- openai/openai-vanilla/deployment/pom.xml
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/ToolsApplicationScopedWithInterceptorTest.java
Originally reported [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/langchain4j.20.2C.20.40tools.20and.20persisting.20with.20Panache/near/417654800)
> Ensure that tools work no matter how the bean was created

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-chroma.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-huggingface.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-pinecone.adoc
When `mvn clean install`-ing the project the docs module introduces these changes
> Integrate doc changes from build

- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
- show error if it happens during search
- wrap long text segments in the results
- mark required text fields as required
> Embedding store Dev UI page improvements

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/NoChatLanguageProviderButCustomBeanTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/NoChatLanguageProviderTest.java
> Don't fail when a user provides a custom model as a bean

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-chroma.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-huggingface.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-pinecone.adoc
- openai/azure-openai/deployment/src/test/java/io/quarkiverse/langchain4j/azure/openai/test/AzureOpenAiChatLanguageModelSmokeTest.java
- openai/azure-openai/deployment/src/test/java/io/quarkiverse/langchain4j/azure/openai/test/WiremockUtils.java
- openai/azure-openai/deployment/src/test/resources/chat/default.json
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiChatModel.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiEmbeddingModel.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/Consts.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiClient.java
- openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/OpenAiChatLanguageModelSmokeTest.java
This is the same as upstream LangChain4j does and was requested my MS in order to be able to determine the use of LangChain4j
> Add user-agent to Azure AI requests

- docs/modules/ROOT/pages/openai.adoc
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiEmbeddingModel.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java
This should have been part of #249 as some of the docs are now out of date because of it.
> Fix deployment-id docs

- README.md
- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/IngestorExampleWithInfinispan.java
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-infinispan.adoc
- docs/modules/ROOT/pages/infinispan-store.adoc
- docs/pom.xml
- docs/src/main/resources/application.properties
Closes https://github.com/quarkiverse/quarkus-langchain4j/issues/297
> Infinispan documentation

- docs/modules/ROOT/pages/infinispan-store.adoc
I realized that the wrong import is in place
> Include Infinispan configuration docs

- redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStore.java
The current implementation uses a separate connection for each embedding being added and tries to execute it all at once, overflowing the pool if there's a lot of embeddings (and unless `quarkus.redis.max-pool-waiting` is adjusted accordingly, it will throw exceptions). With this change, it will create a batch operation and only use one connection.
> Use batching in Redis to avoid overflowing the connection pool

- infinispan/deployment/src/main/java/io/quarkiverse/langchain4j/infinispan/DevServicesConfigBuilderCustomizer.java
- pom.xml
> Updated to Infinispan Dev09

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
When this is done, the @SystemMessage is applied to all the methods, unless overriden by a method
specific annotation
- Closes: #10
> Allow @SystemMessage on an AiService interface

- openai/azure-openai/deployment/src/main/java/io/quarkiverse/langchain4j/azure/openai/deployment/AzureOpenAiProcessor.java
- openai/azure-openai/deployment/src/main/java/io/quarkiverse/langchain4j/azure/openai/deployment/ImageModelBuildConfig.java
- openai/azure-openai/deployment/src/main/java/io/quarkiverse/langchain4j/azure/openai/deployment/Langchain4jAzureOpenAiBuildConfig.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiImageModel.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ImageModelConfig.java
- openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/Langchain4jAzureOpenAiConfig.java
- openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorderEndpointTests.java
- openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/DisabledModelsAzureOpenAiRecorderTest.java
Adding image generation for azure-openai
> Adding image generation for azure-openai

- samples/chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/IngestorExample.java
- samples/chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/RetrieverExample.java
- samples/chatbot/src/main/resources/application.properties
> Cleanup Chatbot example

- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ContentMixin.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ContentTypeMixin.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ContentTypeSerializer.java
- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ImageUrlMixin.java
> Add Content serialization support

- .github/dependabot.yml
- pom.xml
See [this](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Quarkus.203.2E8.20LTS.20Insights.20episode/near/424226569) for more details
> Ensure that the extension shows up in Quarkus tooling for all compatible versions

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-ollama.adoc
- docs/modules/ROOT/pages/llms.adoc
- docs/modules/ROOT/pages/ollama.adoc
- docs/pom.xml
- ollama/devservices/src/main/java/io/quarkiverse/langchain4j/ollama/devservices/OllamaConfig.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ChatModelConfig.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/EmbeddingModelConfig.java
This commit introduces the initial documentation for Ollama:
- Write the ollama documentation
- Change model defaults to be correct
- Explain how to pull model (which then avoid using a dev service)
- Explain how to use the dev service
> Add ollama documentation

- docs/modules/ROOT/pages/ai-services.adoc
- samples/cli-translator/examples/translate.native
> Fix small docs error and introduce runner script for the native compiled cli-translator sample

- core/deployment/src/main/resources/dev-ui/qwc-aiservices.js
- core/deployment/src/main/resources/dev-ui/qwc-chat.js
- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
- core/deployment/src/main/resources/dev-ui/qwc-tools.js
> Small changes to the chat screen

- bam/deployment/src/main/java/io/quarkiverse/langchain4j/bam/deployment/ChatModelBuildConfig.java
- bam/deployment/src/main/java/io/quarkiverse/langchain4j/bam/deployment/EmbeddingModelBuildConfig.java
- bam/deployment/src/test/java/io/quarkiverse/langchain4j/bam/deployment/DefaultPropertiesTest.java
- bam/runtime/src/main/java/io/quarkiverse/langchain4j/bam/BamRestApi.java
- bam/runtime/src/main/java/io/quarkiverse/langchain4j/bam/runtime/config/ChatModelConfig.java
- bam/runtime/src/main/java/io/quarkiverse/langchain4j/bam/runtime/config/EmbeddingModelConfig.java
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/bam.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-bam.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-watsonx.adoc
- docs/modules/ROOT/pages/watsonx.adoc
- docs/pom.xml
- watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/DefaultPropertiesTest.java
- watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ChatModelConfig.java
- watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/LangChain4jWatsonxConfig.java
First documentation release for the `bam` and `watsonx` modules.
One note, I added both modules to the `llms.adoc`, but I don't know if it makes sense for the `bam` module.
> Add bam and watsonx documentation

- core/deployment/src/main/resources/dev-ui/qwc-chat.js
- openai/openai-vanilla/deployment/src/main/resources/dev-ui/qwc-images.js
- openai/openai-vanilla/deployment/src/main/resources/dev-ui/qwc-moderation.js
> Small changes to the Dev UI Images screen

- samples/cli-translator/src/main/java/io/quarkiverse/langchain4j/sample/translator/TranslateCommand.java
- samples/cli-translator/src/main/java/io/quarkiverse/langchain4j/sample/translator/TranslatorAiService.java
E.g. 
$ ./translate.native 
Entering interactive mode: type your text in any language.
Leave an empty line to translate it. Type <CTRL-D> to exit.
Qu'est-ce qui se passé, είπε το γελωτοποιός στον κλέφτη.
"What happened," said the jester to the thief.
$ cat french.txt | ./translate.java 
In a small village nestled in the heart of the French countryside, where fields of lavender stretch as far as the eye can see and the cobbled streets tell tales of yesteryear, lived an old lady known to all for her baking talents. Every morning, she lovingly prepared croissants and pain au chocolat so delicious that even the air seemed to be perfumed by them. The villagers, drawn by the enchanting aroma, crowded into her small bakery at dawn, eager to taste her creations.
Throughout the seasons, the …
> Add the ability to pipe into the translate command/interactive mode

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
> Allow @MemoryId parameters to be template params

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/tool/QuarkusToolExecutor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/tool/ToolInvoker.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/ToolWithToolMemoryIdTest.java
> Support @ToolMemoryId

- milvus/deployment/pom.xml
- milvus/deployment/src/main/java/io/quarkiverse/langchain4j/milvus/MilvusBuildConfig.java
- milvus/deployment/src/main/java/io/quarkiverse/langchain4j/milvus/MilvusDevServicesProcessor.java
- Relates to: https://github.com/quarkiverse/quarkus-langchain4j/issues/329
> Use the MilvusContainer from testcontainers

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
- docs/modules/ROOT/pages/ai-services.adoc
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
Some AiService implementation may not need (or even be hindered by) chat memory, so we now provide
an option to disable it
- Closes: #382
> Add way to disable chat memory

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/json/ChatResultPojo.java
> Support tools in the Chat Dev UI page

- core/deployment/pom.xml
- core/runtime/pom.xml
- integration-tests/devui/pom.xml
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/389
> Don't depend on vertx-http

- core/deployment/src/main/resources/dev-ui/qwc-chat.js
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/json/ChatMessagePojo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/json/ChatResultPojo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/json/MessageType.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/json/ToolExecutionRequestPojo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/json/ToolExecutionResultPojo.java
> Support showing tool-related messages on the Chat page

- chroma/deployment/pom.xml
- chroma/deployment/src/main/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaDevServicesProcessor.java
- milvus/deployment/src/main/java/io/quarkiverse/langchain4j/milvus/MilvusDevServicesProcessor.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/329
> Use ChromaDBContainer from testcontainers

- docs/modules/ROOT/pages/pgvector-store.adoc
- pgvector/deployment/src/main/java/io/quarkiverse/langchain4j/pgvector/deployment/DevServicesConfigBuilderCustomizer.java
- pgvector/deployment/src/main/resources/META-INF/services/io.smallrye.config.SmallRyeConfigBuilderCustomizer
- pgvector/deployment/src/test/java/io/quarkiverse/langchain4j/pgvector/test/LangChain4jPgvectorTest.java
- pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/PgVectorEmbeddingStore.java
> configure devservices datasource image when pgvector is used

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
> Be more defensive when removing chat memory ids

- infinispan/deployment/pom.xml
- infinispan/pom.xml
- infinispan/runtime/pom.xml
- pom.xml
Infinispan Quarkus Langchain 3.9
> Moves Infinispan extension to 3.9

- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
> Fix embedding store page in Dev UI

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mistralai.adoc
- docs/modules/ROOT/pages/mistral.adoc
@geoand, as discussed together (#425), here is a first version of a documentation for Mistral configuration.
The doc could be updated in the future with examples.
> feat: 📝 add configuration doc for Mistral AI

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
- openai/openai-vanilla/deployment/src/test/resources/messages/recipe-user.txt
- openai/openai-vanilla/deployment/src/test/resources/messages/translate-system
- openai/openai-vanilla/deployment/src/test/resources/messages/translate-user.txt
> Support fromResource for user and system messages

- core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusPromptTemplateFactory.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/LangChain4jRecorder.java
- openai/openai-vanilla/devmode-tests/pom.xml
- openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/Configuration.java
- openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/ConfigurationKey.java
- openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/PromptDevModeTest.java
- openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/Resource.java
- openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/Service.java
- openai/openai-vanilla/pom.xml
- Fixes: #436
~~_Opening as a draft as I need to create a test_~~
> Ensure that templates don't cause CL issues during reload

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mistralai.adoc
- docs/modules/ROOT/pages/llms.adoc
- docs/pom.xml
Add elements to be in the toc page and the [LLMs](https://docs.quarkiverse.io/quarkus-langchain4j/dev/llms.html) page.
@geoand sorry but I didn't master the build tools and the testing phase for the documentation in the previous PR 😅.
> doc: 🐛 fix nav links

- core/deployment/src/main/resources/dev-ui/qwc-chat.js
- Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/463
> Show errors in the chat page

- openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java
I'm not completely sure it's sensitive, but I'd assume it is?!
> Mask the value of Set-Cookie headers

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
> Allow user message to be a template

- samples/csv-chatbot/pom.xml
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/CsvIngestorExample.java
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/Movie.java
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/MovieDatabaseContentRetriever.java
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/MovieMuseSupport.java
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/MovieSchemaSupport.java
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/MovieTableIntegrator.java
- samples/csv-chatbot/src/main/resources/META-INF/services/org.hibernate.integrator.spi.Integrator
- samples/csv-chatbot/src/main/resources/application.properties
- samples/csv-chatbot/src/main/resources/data/movies.csv
> Improve the csv-chatbot sample

- samples/chatbot-easy-rag/README.md
- samples/chatbot-easy-rag/README.txt
- samples/chatbot/README.md
- samples/cli-translator/README.md
- samples/csv-chatbot/README.md
- samples/email-a-poem/README.md
- samples/email-a-poem/src/main/resources/application.properties
- samples/review-triage/README.md
Also adds configuration and instructions for a mock SMTP server to the `email-a-poem` sample to be able to actually see the sent email
> Add READMEs to all samples

- samples/chatbot-easy-rag/pom.xml
- samples/chatbot/pom.xml
- samples/cli-translator/pom.xml
- samples/csv-chatbot/pom.xml
- samples/email-a-poem/pom.xml
- samples/fraud-detection/pom.xml
This makes the samples work OOTB with Maven 3.8
> Override the maven-compiler-plugin version in the samples

- easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagConfig.java
- easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagRecorder.java
- easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/IngestionStrategy.java
This partially resolves https://github.com/quarkiverse/quarkus-langchain4j/issues/473
The other two strategies are doable, but right now it would be a bit tricky
> Ability to turn off ingestion with Easy RAG

- .github/dependabot.yml
Since we have now made the sample self-contained,
let's also have them updated when we release a
new version
> Introduce dependabot updates for samples

- core/deployment/src/main/resources/dev-ui/qwc-chat.js
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/519
> Remove timestamps from chat messages for now

- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
> Properly catch JSON-RPC errors when adding embeddings

- docs/modules/ROOT/pages/index.adoc
Thought this might be important and interesting enough to mention on the main page...
> Add a little tip about quarkus.langchain4j.log-requests/responses

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/OpenNlpProcessor.java
- core/runtime/pom.xml
- docs/modules/ROOT/pages/in-process-embedding.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-anthropic.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-bam.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mistralai.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-ollama.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j.adoc
- easy-rag/deployment/pom.xml
- integration-tests/embed-all-minilm-l6-v2-q/pom.xml
- integration-tests/embed-all-minilm-l6-v2/pom.xml
- integration-tests/embed-bge-small-en-q/pom.xml
- integration-tests/embed-bge-small-en/pom.xml
- integration-tests/embed-e5-small-v2-q/pom.xml
- integration-tests/embed-e5-small-v2/pom.xml
- parsers-base/deployment/pom.xml
- parsers-base/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/parsers/base/DocumentSupportProcessor.java
- parsers-base/pom.xml
- parsers-base/runtime/pom.xml
- parsers-base/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- parsers-base/runtime/src/main/resources/META-INF/services/io.quarkiverse.langchain4j.spi.DefaultMemoryIdProvider
- pom.xml
- samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/ImportmapResource.java
- samples/csv-chatbot/src/main/resources/application.properties
The reason we don't want these in the core module
is because not every application needs the doc
parsing functionality (which adversely affects the application size).
For example, a simple AiService that uses OpenAI  has at least 30MB 
added to binary size by just including the POI and BouncyCastle dependencies.
We might need to make this module (or some derivatives of it) more explicit
in the docs and / or by using conditional dependencies.
> Move the parsers out of the core module

- anthropic/deployment/src/test/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicChatLanguageModelSmokeTest.java
- anthropic/deployment/src/test/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicStreamingChatLanguageModelSmokeTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java
This is done so that when we log the body, it is
pretty printed.
- Closes: #549
> Send pretty printed JSON body

- samples/email-a-poem/src/main/java/io/quarkiverse/langchain4j/sample/MyAiService.java
- samples/email-a-poem/src/main/resources/META-INF/resources/index.html
Resolves: #563
So, the pull request adds a minimal index.html that provides a UI for Email me a poem.
It also catches errors and hints users.
Note, the UI is as minimal as it gets (no vaadin components here) for minimalism shake. If we prefer to have a consistent UI all across our samples, I am all for aligning.
**edit**: The PR also improves the prompt, so that the poem is actually displayed in the response.
> Add minimal html  UI for email me a peom

- samples/fraud-detection/README.md
- samples/fraud-detection/src/main/resources/application.properties
The PR bumps the model used for distance fraud detection to gpt-4 and also updates the readme.
> Fix distance fraud detection

- samples/email-a-poem/README.md
The description mentions chat-bot, RAG and PostgreSQL which seems to me like a copy and paste mistake.
This pull request provides a more accurate description.
> Fix description of email-me-a-poem

- samples/fraud-detection/src/main/java/io/quarkiverse/langchain4j/sample/Setup.java
The pull request, improves the Setup of class of the fraud-detection sample, so that there are definitely frauds to report.
> Setup now ensures there are frauds to report

- samples/review-triage/src/main/resources/META-INF/resources/components/demo-review.js
> Add hints in the triage review page

- docs/modules/ROOT/pages/ollama.adoc
- ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaAuthenticationHeaderTest.java
Relates to: https://github.com/langchain4j/langchain4j/issues/586
> Add documentation on using authentication headers with Ollama

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/LangChain4jDevUIProcessor.java
- core/deployment/src/main/resources/dev-ui/qwc-chat.js
> When there is a single SystemMessage expose set it to dev ui.

- anthropic/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- bam/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- chroma/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- cohere/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- easy-rag/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- hugging-face/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- infinispan/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- memory-store-redis/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- milvus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- mistral/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- ollama/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- openai/azure-openai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- openai/openai-vanilla/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- openshift-ai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- parsers-base/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- pgvector/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- pinecone/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- qdrant/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- redis/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- vertex-ai-gemini/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- vertex-ai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- watsonx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- websockets-next/runtime/src/main/resources/META-INF/quarkus-extension.yaml
> Add missing guide link in extensions

- core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js
> Use vaadin progress bar in dev-ui embedding store

- openai/openai-vanilla/deployment/src/main/resources/dev-ui/qwc-images.js
> Apply model constraints to image ui combos

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-ollama.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j.adoc
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ChatResponse.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/OllamaRecorder.java
- ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ChatModelConfig.java
This way Ollama can decide what the default should be (if any)
> Make token limit configuration for Ollama optional

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/SpanWrapper.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/tool/ToolSpanWrapper.java
All we need is the tracing APIs, not the general
instrumentation APIs
> Simplify OpenTelemetry instrumentation code

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- Relates to: https://github.com/quarkusio/quarkus/issues/40854
> Fix issue with reload when tools are new added

- docs/modules/ROOT/nav.adoc
Mistral AI was listed twice in the nav
> Mistral listed twice in nav

- rag/parsers-base/runtime/src/main/resources/META-INF/services/io.quarkiverse.langchain4j.spi.DefaultMemoryIdProvider
> Remove erroneously added service file

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-chroma.adoc
- embedding-stores/chroma/deployment/src/test/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaEmbeddingStoreCDITest.java
- embedding-stores/chroma/deployment/src/test/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaEmbeddingStoreTest.java
- embedding-stores/chroma/runtime/src/main/java/io/quarkiverse/langchain4j/chroma/ChromaEmbeddingStore.java
- embedding-stores/chroma/runtime/src/main/java/io/quarkiverse/langchain4j/chroma/runtime/ChromaConfig.java
- embedding-stores/chroma/runtime/src/main/java/io/quarkiverse/langchain4j/chroma/runtime/ChromaRecorder.java
I have no idea why the test started failing, or why this hack (removing embeddings twice) fixes it (but it seems to do so) - but it's just for tests so it should be ok
While troubleshooting this, I found it useful to add proper logging for Chroma.
> Implement logging for Chroma and attempt to fix the test

- model-providers/ollama/devservices/src/main/java/io/quarkiverse/langchain4j/ollama/devservices/OllamaContainer.java
a very small typo when looking for configured models
> (doc) small ollama typo

- core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/chroma/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/infinispan/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/milvus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/pgvector/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/pinecone/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/qdrant/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- embedding-stores/redis/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- memory-stores/memory-store-redis/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/anthropic/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/bam/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/cohere/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/hugging-face/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/mistral/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/ollama/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/openai/azure-openai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/openai/openai-vanilla/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/openshift-ai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/vertex-ai-gemini/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/vertex-ai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- model-providers/watsonx/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- quarkus-integrations/websockets-next/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- rag/easy-rag/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- rag/parsers-base/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Waiting for "code.quarkus.io" to have an AI category (Ping @ia3andy).
> Switch category of extensions to AI

- docs/modules/ROOT/pages/ollama.adoc
fix #722 
Small update to the documentation to fix the issue for filters and native compilation.
> doc: 📝 Add information about native compilation for Ollama

- embedding-stores/pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/PgVectorAgroalPoolInterceptor.java
> Don't run CREATE EXTENSION IF NOT EXISTS vector in prod mode

- samples/chatbot-easy-rag/README.md
- samples/chatbot/README.md
- samples/cli-translator/README.md
- samples/review-triage/README.md
> Document Ollama and OpenAI compatible serving in samples

- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java
> Stop skipping Ollama responses with whitespaces

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-ollama.adoc
- docs/modules/ROOT/pages/ollama.adoc
- model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaAuthenticationHeaderTest.java
- model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaChatLanguageModelSmokeTest.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ChatModelFixedRuntimeConfig.java
See https://ai.meta.com/blog/meta-llama-3-1/ for more details
> Use llama3.1 as the default Ollama model

- core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
> Improve JSON sanitize

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/QuarkusServiceOutputParser.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
> Make Multi<String> AiService work with RAG

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/EmbeddingStoreJsonRPCService.java
- embedding-stores/chroma/deployment/src/main/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaProcessor.java
- embedding-stores/infinispan/deployment/src/main/java/io/quarkiverse/langchain4j/infinispan/InfinispanEmbeddingStoreProcessor.java
- embedding-stores/milvus/deployment/src/main/java/io/quarkiverse/langchain4j/milvus/MilvusProcessor.java
- embedding-stores/neo4j/deployment/src/main/java/io/quarkiverse/langchain4j/neo4j/Neo4jEmbeddingStoreProcessor.java
- embedding-stores/pgvector/deployment/src/main/java/io/quarkiverse/langchain4j/pgvector/deployment/PgVectorEmbeddingStoreProcessor.java
- embedding-stores/pinecone/deployment/src/main/java/io/quarkiverse/langchain4j/pinecone/PineconeProcessor.java
- embedding-stores/qdrant/deployment/src/main/java/io/quarkiverse/langchain4j/qdrant/QdrantProcessor.java
- embedding-stores/redis/deployment/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStoreProcessor.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/786
> Fix embedding model handling with Easy RAG

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-easy-rag.adoc
- rag/easy-rag/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/EasyRagProcessor.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagManualTriggerTest.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/EasyRagManualIngestion.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagConfig.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagIngestor.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagRecorder.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/IngestionStrategy.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/765
@lordofthejars
> Introduce the MANUAL ingestion strategy for Easy RAG

- embedding-stores/milvus/deployment/pom.xml
- embedding-stores/milvus/deployment/src/test/java/io/quarkiverse/langchain4j/milvus/deployment/MilvusMetadataFilteringTest.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/797
> Introduce some basic metadata filtering tests for Milvus

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
> Support LangChain4j's Result return type

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/SystemMessageNonExistingResourceTest.java
> Properly handle resource missing case for user and system messages

- model-providers/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertxAiGeminiRestApi.java
> Add Bearer scheme in the default Vertex AI Gemini authentication filter

- core/deployment/pom.xml
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/BlockingChatLanguageModelSupplierTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/StreamingAndBlockingChatLanguageModelSupplierTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/StreamingChatLanguageModelSupplierTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DeclarativeAiServiceCreateInfo.java
This is need to support custom `StreamingChatLanguageModel` in Ai Services
- Closes: #842
> Add `streamingChatLanguageModelSupplier` property to `@RegisterAiService`

- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModel.java
Not sure why but it fails the build for me? Are you all building inside Intellij?
> Drop a jetbrains annotation

- samples/chatbot-easy-rag/pom.xml
- samples/chatbot-web-search/pom.xml
- samples/chatbot/pom.xml
- samples/cli-translator/pom.xml
- samples/email-a-poem/pom.xml
- samples/fraud-detection/pom.xml
- samples/review-triage/pom.xml
- samples/secure-fraud-detection/pom.xml
- samples/secure-vertex-ai-gemini-poem/pom.xml
- samples/sql-chatbot/pom.xml
For such a large project, I highly recommend the use of `mvnd` and one of the condition to use it is to make sure the project is properly constrained, thus these additions.
> Constrain the build for better compatibility with mvnd

- docs/modules/ROOT/pages/watsonx.adoc
- model-providers/watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/WatsonxProcessor.java
- model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/PromptFormatterExceptionTest.java
- model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/PromptFormatterModelTest.java
- model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/PromptFormatterToolsTest.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxModel.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/PromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/PromptFormatterMapper.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/PromptFormatterUtil.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/PromptToolFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/GraniteCodePromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/GranitePromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/Llama31PromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/LlamaPromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/LlamaToolFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/MistralLargePromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/MistralLargeToolFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/MistralPromptFormatter.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/prompt/impl/NoopPromptFormatter.java
Added the ability to use tools with models:
- `meta-llama/llama-3-405b-instruct`
- `meta-llama/llama-3-1-70b-instruct`
> [WATSONX] Enable tool functionality for the model llama3.1

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/GuardrailWithAugmentationTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputAndOutputGuardrailsTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailChainTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailNotFoundTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailOnClassAndMethodTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailOnClassTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailValidationTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailChainTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailNotFoundTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailOnClassAndMethodTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailOnClassTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailRepromptingRetryDisabledTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailRepromptingTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailValidationTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/GuardrailException.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrail.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrails.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrail.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrails.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java
- docs/modules/ROOT/pages/guardrails.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-easy-rag.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-watsonx.adoc
This is the counterpart of the output guardrails. 
This PR also refactors the output guardrail mechanism to allow the sharing of some code between both sides.
> Initial code around the input guardrails idea

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- integration-tests/openai/src/main/java/org/acme/example/openai/chat/ChatLanguageModelResource.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
Reported independently by @gsmet and @mariofusco
> Fix primitive handling of AiServices

- samples/chatbot-easy-rag/pom.xml
- samples/chatbot-easy-rag/src/main/resources/META-INF/resources/components/demo-chat.js
- samples/chatbot-web-search/pom.xml
- samples/chatbot-web-search/src/main/resources/META-INF/resources/components/demo-chat.js
- samples/chatbot/pom.xml
- samples/chatbot/src/main/resources/META-INF/resources/components/demo-chat.js
- samples/sql-chatbot/pom.xml
- samples/sql-chatbot/src/main/resources/META-INF/resources/components/demo-chat.js
replaces https://github.com/quarkiverse/quarkus-langchain4j/pull/890
> Hide the 'loading' bubbles in chatbot samples

- docs/modules/ROOT/pages/in-process-embedding.adoc
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/898
> Update packages of in-process embeddings in the docs

- embedding-stores/redis/deployment/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStoreProcessor.java
- embedding-stores/redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStore.java
- embedding-stores/redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/runtime/RedisEmbeddingStoreRecorder.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/896
> Use QueryArgs.param or dialect depending on the Quarkus version

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/items/MethodParameterIgnoredAnnotationsBuildItem.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/AiServiceMethodParametersAnnotationsTest.java
> Make AI service parameters ignored annotations configurable

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DotNames.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/ImageUrl.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- docs/modules/ROOT/pages/ai-services.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
- integration-tests/openai/src/main/java/org/acme/example/openai/aiservices/DescribeImageResource.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
~~_P.S. Needs Javadoc, docs and tests_~~
> Add the ability to describe an image via AiService

- pom.xml
Reverts quarkiverse/quarkus-langchain4j#928
> Revert "Bump langchain4j-embeddings.version from 0.34.0 to 0.35.0"

- core/runtime/src/main/java/io/quarkiverse/langchain4j/cost/Cost.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/cost/CostEstimator.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/cost/CostEstimatorService.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/listeners/MetricsChatModelListener.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/listeners/SpanChatModelListener.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/cost/BasicE3BigCostEstimator.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/cost/BasicE3SmallCostEstimator.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/cost/BasicGpt4oCostEstimator.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/cost/BasicGpt4oMiniCostEstimator.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/cost/BasicO1MiniCostEstimator.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/cost/BasicO1PreviewCostEstimator.java
- samples/email-a-poem/src/main/resources/application.properties
> Introduce a way to estimate the cost of an API call

- docs/pom.xml
- docs/src/main/resources/application.properties
- docs/src/test/java/io/quarkiverse/langchain4j/docs/it/AntoraTest.java
- pom.xml
@cescoffier @maxandersen could you please try whether this solves your problems?
> Upgrade to Quarkus Antora - fix issues on Arm Macs

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
> Avoid duplicating info for AiService implementation constructors

- model-providers/anthropic/deployment/src/main/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicProcessor.java
- model-providers/vertex-ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/VertexAiGeminiProcessor.java
- model-providers/vertex-ai/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/deployment/VertexAiProcessor.java
> Anthropic chat model not available when enabled

- model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/JlamaChatModel.java
- model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/runtime/JlamaAiRecorder.java
- model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/runtime/config/LangChain4jJlamaConfig.java
> Add optional logging to jlama requests and responses

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolsMetadataBeforeRemovalBuildItem.java
> Don't include tools from removed beans in the ToolsMetadata

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InvalidOutputGuardrailAccumulatorTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailAccumulatorNotFoundTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailAccumulatorTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailAccumulatorWithoutGuardrailTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailChainOnStreamedResponseTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailOnStreamedResponseTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailOnStreamedResponseValidationTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailAccumulator.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputTokenAccumulator.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java
- docs/modules/ROOT/pages/guardrails.adoc
The user can implement a custom accumulator to decide when to invoke the guardrail chain.
> Implement support for output guardrail on streamed responses

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-jlama.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/jlama.adoc
- docs/modules/ROOT/pages/llms.adoc
> Add Jlama documentation

- pom.xml
> Bump jlama to version 0.8.1

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devservice/DevServicesOllamaProcessor.java
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-tavily.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-tavily_quarkus.langchain4j.adoc
- model-providers/jlama/deployment/src/main/java/io/quarkiverse/langchain4j/jlama/deployment/JlamaProcessor.java
- model-providers/llama3-java/deployment/src/main/java/io/quarkiverse/langchain4j/llama3/deployment/Llama3Processor.java
This change includes two things:
* Ration progress log updates
* Include model name in progress log
Originally started because of #1044, but it also handles: #1046 
- Closes: #1044
- Closes: #1046
> Improve model download progress logging

- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/auth/AllModelAuthProvidersTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/auth/GeminiModelAuthProvider.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/auth/GlobalModelAuthProvider.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/auth/GlobalModelAuthProviderTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/auth/NamedModelAuthProvidersTest.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/auth/OpenaiModelAuthProvider.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/auth/ModelAuthProvider.java
Fixes #1038
@csotiriou @geoand Please review
> Allow using generic ModelAuthProvider with named models

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
- integration-tests/multiple-providers/src/main/resources/application.properties
- integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleChatProvidersTest.java
- integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleEmbeddingModelsTest.java
- integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleModerationProvidersTest.java
- integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleScoringModelsTest.java
- Closes: #1059 
Just a draft to show how to enable injection even for models that do not have explicit injection points.
> Register all models from configuration as beans regardless of the existance of injection point

- .github/workflows/build-pull-request.yml
- pom.xml
I will probably have to tweak things a bit but this is preparatory work.
Let me merge it as I want to check a few things first.
> Prepare the arrival of the bot

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-tavily.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-tavily_quarkus.langchain4j.adoc
- embedding-stores/chroma/deployment/src/main/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaProcessor.java
- embedding-stores/pinecone/deployment/src/main/java/io/quarkiverse/langchain4j/pinecone/PineconeProcessor.java
- model-providers/anthropic/deployment/src/main/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicProcessor.java
- model-providers/cohere/deployment/src/main/java/io/quarkiverse/langchain4j/cohere/CohereProcessor.java
- model-providers/hugging-face/deployment/src/main/java/io/quarkiverse/langchain4j/huggingface/deployment/HuggingFaceProcessor.java
- model-providers/mistral/deployment/src/main/java/io/quarkiverse/langchain4j/mistralai/deployment/MistralAiProcessor.java
- model-providers/ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaProcessor.java
- model-providers/openai/openai-common/deployment/src/main/java/io/quarkiverse/langchain4j/openai/common/OpenAiCommonProcessor.java
- model-providers/openshift-ai/deployment/src/main/java/io/quarkiverse/langchain4j/openshift/ai/deployment/OpenshiftAiProcessor.java
- model-providers/vertex-ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/VertexAiGeminiProcessor.java
- model-providers/vertex-ai/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/deployment/VertexAiProcessor.java
- model-providers/watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/WatsonxProcessor.java
- tools/tavily/deployment/src/main/java/io/quarkiverse/langchain4j/tavily/deployment/TavilyProcessor.java
> Prioritize Jackson over Jsonb in extension that use `quarkus-rest-client-jackson`

- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java
Handle MismatchedInputException in catch-clause.
It is either wrapped in ClientWebApplicationException with Status 400 or wrapped in ProcessingException depending on the Quarkus version.
See #685.
The diff display is a bit misleading, i only changed the catch and if clause + indentation.
Handling both cases in a single catch makes the if-clause a bit unwieldy, but two catch-clauses and extraction of the body to avoid code duplication was not really practical either.
> Fix MismatchedInputException in Ollama streaming

- integration-tests/jlama/pom.xml
- integration-tests/llama3-java/pom.xml
This to tentatively fix Ecosystem CI.
> Drop references to resteasy-reactive artifacts

- model-providers/anthropic/deployment/src/test/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicStreamingChatLanguageModelSmokeTest.java
- model-providers/anthropic/runtime/src/main/java/io/quarkiverse/langchain4j/anthropic/QuarkusAnthropicClient.java
- Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1089
> Remove duplicate invocation from handleMessageStop.

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mistral-ai.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mistral-ai_quarkus.langchain4j.adoc
- model-providers/mistral/deployment/src/main/java/io/quarkiverse/langchain4j/mistralai/deployment/LangChain4jMistralAiBuildConfig.java
- model-providers/mistral/deployment/src/main/java/io/quarkiverse/langchain4j/mistralai/deployment/MistralAiProcessor.java
- model-providers/mistral/deployment/src/main/java/io/quarkiverse/langchain4j/mistralai/deployment/ModerationModelBuildConfig.java
- model-providers/mistral/deployment/src/test/java/io/quarkiverse/langchain4j/mistralai/deployment/MistralAiModerationModelSmokeTest.java
- model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/runtime/MistralAiRecorder.java
- model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/runtime/config/LangChain4jMistralAiConfig.java
- model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/runtime/config/ModerationModelConfig.java
> Integrate Mistral AI moderation models

- model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaStreamingChatLanguageModelSmokeTest.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModel.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ToolCall.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatMessage.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/client/WatsonxRestApi.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/client/filter/BearerTokenHeaderFactory.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
Resolves: #795
Resolves: #988 
To use tools with streaming it is important to update Ollama to 0.4.6.
> Enable tools support in streaming responses for Ollama

- model-providers/ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaProcessor.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/OllamaRecorder.java
- model-providers/openai/azure-openai/deployment/src/main/java/io/quarkiverse/langchain4j/azure/openai/deployment/AzureOpenAiProcessor.java
- model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiChatModel.java
- model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java
- model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
- model-providers/openai/openai-vanilla/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/OpenAiProcessor.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
- model-providers/openai/openai-vanilla/runtime/src/test/java/io/quarkiverse/langchain4j/openai/runtime/DisabledModelsOpenAiRecorderTest.java
> Introduce observability into streaming models

- model-providers/openai/azure-openai/deployment/src/main/java/io/quarkiverse/langchain4j/azure/openai/deployment/AzureOpenAiProcessor.java
- model-providers/openai/azure-openai/deployment/src/test/java/io/quarkiverse/langchain4j/azure/openai/test/ModelAuthProviderSmokeTest.java
> Fix ModelAuthProvider for streaming chat model in Azure

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1129
> Fix registration of embedding model for Easy RAG

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-pgvector.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-pgvector_quarkus.langchain4j.adoc
- embedding-stores/pgvector/deployment/src/main/java/io/quarkiverse/langchain4j/pgvector/deployment/PgVectorEmbeddingStoreProcessor.java
- embedding-stores/pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/PgVectorAgroalPoolInterceptor.java
- embedding-stores/pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/runtime/PgVectorEmbeddingStoreConfig.java
- embedding-stores/pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/runtime/PgVectorEmbeddingStoreRecorder.java
Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1139
> Pass configs and an extension value to make sure vector extensions are created and can be overridden by passing that config

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ObjectSubstitutionUtil.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonArraySchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonBooleanSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonEnumSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonIntegerSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonNumberSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonObjectSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonReferenceSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/substitution/JsonStringSchemaObjectSubstitution.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/types/TypeUtil.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/StructuredOutputResponseTest.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ChatModelConfig.java
> Add support for structured output in OpenAI

- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/GuardrailResult.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrailResult.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailResult.java
- docs/modules/ROOT/pages/guardrails.adoc
- testing/core/pom.xml
- testing/core/src/main/java/io/quarkiverse/langchain4j/guardrails/GuardrailAssertions.java
- testing/core/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailResultAssert.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/ClaimInfo.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailContainsRequiredInformationOutputGuardrail.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailContainsRequiredInformationOutputGuardrailTests.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailEndsAppropriatelyOutputGuardrail.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailEndsAppropriatelyOutputGuardrailTests.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailStartsAppropriatelyOutputGuardrail.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailStartsAppropriatelyOutputGuardrailTests.java
- testing/pom.xml
@geoand @cescoffier this is based on the conversation we had internally.
> Add a core testing module with some custom AssertJ assertions for output guardrails

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/tool/QuarkusToolExecutor.java
- model-providers/vertex-ai-gemini/runtime/src/test/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertxAiGeminiRestApiTokenFilterTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagTest.java
- tools/tavily/deployment/src/test/java/io/quarkiverse/langchain4j/tavily/test/TavilyTest.java
Unused and star imports cleanup
> Unused and star imports cleanup

- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/qdrant-store.adoc
> Add Qdrant document store documentation

- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/Audit.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/AuditService.java
- docs/modules/ROOT/pages/ai-services.adoc
Deprecate existing auditing stuff based on #1217
Fixes #1218
> Deprecate auditing stuff

- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrailParams.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailParams.java
- testing/core/src/test/java/io/quarkiverse/langchain4j/guardrails/EmailContainsRequiredInformationOutputGuardrailTests.java
Introducing a few simple factory methods for creating `InputGuardrailParams` and `OutputGuardrailParams`.
> Introducing some factory methods for creating guardrail params

- docs/modules/ROOT/pages/ai-services.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-azure-openai.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-azure-openai_quarkus.langchain4j.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java_quarkus.langchain4j.adoc
Clarify a bit the usage of more than one model of the same kind of provider (e.g. chat and embedd), that sit on different URLs. Also mention the usage of `@ModelName`, which was not listed in the docs.
This is a result of #1220
> Clarify usage of multiple models in one process

- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/IngestorExampleWithMilvus.java
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/milvus-store.adoc
- docs/pom.xml
- docs/src/main/resources/application.properties
> Add a page about the Milvus store.

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/template/ChatMessageTemplateExtension.java
- model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/MessageMapper.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxGenerationModel.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatMessage.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1246
> Ensure there's default handling in place for switch statements involving LangChain4j ChatMessage types

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
> Make maximum number of tool executions configurable

- docs/modules/ROOT/pages/mcp.adoc
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1252
> Add MCP configuration reference to the docs page

- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/AiChatServiceTest.java
- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatAllPropertiesTest.java
- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatDefaultPropertiesTest.java
- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/GenerationAllPropertiesTest.java
- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ToolNotFoundTest.java
- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/UnsupportedResponseFormatTest.java
- model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/WireMockUtil.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/Watsonx.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatRequestParameters.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxGenerationModel.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxGenerationRequestParameters.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatMessage.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatParameters.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatRequest.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextGenerationParameters.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextGenerationResponse.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextStreamingChatResponse.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
- model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ChatModelConfig.java
I implemented the new `chat` method that was added in the latest version of lanchain4j
> Update watsonx.ai module to Langchain4j 1.0.0-beta1

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/RestClientToolboxTest.java
This was originally found by @iocanel
> Allow Rest Client and AI Service to be used in `@Toobox`

- model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiChatLanguageModel.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/Blob.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/ContentMapper.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/FileData.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GenerateContentRequest.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GenerationConfig.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/Schema.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/SchemaMapper.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/Type.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiChatLanguageModel.java
- Closes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1285
> Add PDF support to Google Gemini models

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/JsonTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/PdfUrl.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/CustomLocalDateDeserializer.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/CustomLocalDateTimeDeserializer.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/CustomLocalTimeDeserializer.java
- model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiChatLanguageModel.java
This allows for declarative handling of PDF content in AiServices in much the same way as @ImageUrl
does
- Closes: #1294
> Introduce @PdfUrl

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
Before this commit, only Fault Tolerance was supported in an ad-hoc manner.
With this change, all annotations that trigger
a CDI interceptor are now supported on methods
of AiService.
Relates to: #1314
> Add proper support for CDI interceptors in AiService methods

- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiChatLanguageModel.java
I just copied some code from #1306 to keep it in sync, so that I can easily update both providers to handle ChatModelListener
> Response type support for Vertex AI Gemini

- model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiRestApi.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/EmbedContentRequest.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/EmbedContentRequests.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/EmbedContentResponse.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/EmbedContentResponses.java
- model-providers/google/vertex-ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/LangChain4jVertexAiBuildConfig.java
- model-providers/google/vertex-ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/LangChain4jVertexAiEmbeddingConfig.java
- model-providers/google/vertex-ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/VertexAiGeminiProcessor.java
- model-providers/google/vertex-ai-gemini/deployment/src/test/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/VertexAiGeminiEmbeddingModelSmokeTest.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiEmbeddingModel.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiRecorder.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertxAiGeminiRestApi.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/config/LangChain4jVertexAiGeminiConfig.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/config/LangChain4jVertexAiGeminiEmbeddingConfig.java
Aligning AiGemini with VertexAiGemini to support EmbeddingModel, based on the work of @lordofthejars.
I think we'll have more opportunities to push to the common gemini module later :-), since both providers are nearly identical, with some configuration differences.
@lordofthejars @geoand, please review
> Support EmbeddingModel for VertexAi Gemini

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- docs/modules/ROOT/pages/ai-services.adoc
- integration-tests/openai/src/test/java/org/acme/example/openai/aiservices/AssistantResourceWithMetricsTest.java
- Originally reported at https://github.com/cescoffier/langchain4j-deep-dive/issues/79
> Fix duplicate names in metrics registration

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/MultipleChatModelsDeclarativeServiceTest.java
This allows callers to override the default ChatLanguageModel configured for the AiService.
- Closes: #1109
> Support @ModelName as an AiService method parameter

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/listeners/PromptTextSpanContributor.java
Relates to: https://github.com/quarkiverse/quarkus-langchain4j/issues/1349#issuecomment-2728512328
> Fix prompt span attribute name

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp_quarkus.langchain4j.adoc
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpClientConfig.java
> Add the resources-timeout property for MCP clients

- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/ImageModelTest.java
- model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiImageModel.java
- model-providers/openai/testing-internal/src/main/resources/openai/mappings/completions.json
> Fix image generation request issue

- model-providers/jaxrs-client/src/main/java/io/quarkiverse/langchain4j/jaxrsclient/JaxRsHttpClient.java
> Properly make JaxRsHttpClient with Quarkus SNAPSHOT

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
Reproducer - https://github.com/xstefank/quarkus-reproducers/tree/main/lc4j-custom-model-native. Just run `-Dnative` with tests.
> Fix native registration of user-provided model classes

- mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpConfigFileContentsBuildItem.java
- mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpProcessor.java
- mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpClaudeConfigTest.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/ClaudeDesktopConfigSourceProvider.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/LocalLaunchParams.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpBuildTimeConfiguration.java
- mcp/runtime/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSourceProvider
> Support Claude Desktop config file

- samples/mcp-sse-client-server/mcp-client/pom.xml
- samples/mcp-sse-client-server/mcp-client/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/AiWeatherService.java
- samples/mcp-sse-client-server/mcp-client/src/main/resources/application.properties
- samples/mcp-sse-client-server/mcp-server/pom.xml
- samples/mcp-sse-client-server/mcp-server/src/main/java/io/quarkiverse/langchain4j/sample/Weather.java
- samples/mcp-sse-client-server/mcp-server/src/main/resources/application.properties
This came up during a presentation that @kdubois @dandreadis @iocanel and I were doing
> Fix empty text error in MCP weather sample

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp_quarkus.langchain4j.adoc
- mcp/deployment/pom.xml
- mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpProcessor.java
- mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpHealthCheckTest.java
- mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/MockHttpMcpServer.java
- mcp/runtime/pom.xml
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpClientHealthCheck.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpBuildTimeConfiguration.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpClientRuntimeConfig.java
- samples/mcp-tools/pom.xml
- Closes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1414
> MP Health check for MCP clients, plus configurable ping timeout

- docs/modules/ROOT/pages/agent-and-tools.adoc
> Document tool parameter naming convention (snake_case)

- testing/scorer/scorer-strategies/semantic-similarity/src/main/java/io/quarkiverse/langchain4j/testing/scorer/similarity/SemanticSimilarityStrategy.java
> Show actionable error message when testing-scorer used without bge-small-en-v15

- docs/modules/ROOT/pages/mcp.adoc
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpToolBox.java
- samples/mcp-sse-client-server/mcp-client/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/AiWeatherService.java
- samples/mcp-tools/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/Bot.java
> Document @McpToolBox annotation and fix samples

- model-providers/cohere/runtime/src/main/java/io/quarkiverse/langchain4j/cohere/runtime/api/CohereApi.java
- model-providers/cohere/runtime/src/main/java/io/quarkiverse/langchain4j/cohere/runtime/config/Langchain4jCohereConfig.java
Updates the API of ranking when using Cohere: https://docs.cohere.com/reference/rerank
> Fix reranking cohere API

- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/ProgrammaticServiceConfigurationTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
Fix issue discussed here https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/Quarkus.20LangChain4J.20SystemMessageProvider/with/517584529
/cc @geoand
> Use programmatically provided system message if present

- mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpProcessor.java
> Properly make MCP Client Health check actually optional

- samples/chatbot-easy-rag-kotlin/README.md
- samples/chatbot-easy-rag-kotlin/catalog/easytrade-starter-portfolio.md
- samples/chatbot-easy-rag-kotlin/pom.xml
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/Assistant.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/ChatBotWebSocket.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/tools/CurrentTime.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/tools/CustomerCallbackScheduler.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/tools/MarketData.kt
- samples/chatbot-easy-rag-kotlin/src/main/resources/META-INF/resources/components/demo-title.js
- samples/chatbot-easy-rag-kotlin/src/main/resources/application.properties
- samples/chatbot-easy-rag-kotlin/src/main/resources/prompts/assistant-system-prompt.md
- Updated Kotlin version to 2.1.21 for better compatibility and enhancements.
- Added `quarkus-langchain4j-memory-store-redis` dependency to support Redis-based memory storage in the chatbot application.
- Adjusted README title to reflect Kotlin usage.
- Move system prompt to resource. Update prompt
- Update time tool to return date as string
- Update assistant and websocket handler
- Update MarketData tool to generate stocks once
- Update demo title page
> Kotlin RAG sample: Update Kotlin, use Redis for embeddings and memory store

- samples/chatbot-easy-rag-kotlin/pom.xml
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/Assistant.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/AssistantExtensions.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/AssistantService.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/ChatBotWebSocket.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/Models.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/sentiment/SentimentAnalyzer.kt
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/tools/CustomerCallbackScheduler.kt
- samples/chatbot-easy-rag-kotlin/src/main/resources/META-INF/resources/components/demo-chat.js
- samples/chatbot-easy-rag-kotlin/src/main/resources/application.properties
- samples/chatbot-easy-rag-kotlin/src/main/resources/prompts/assistant-system-prompt.md
- samples/chatbot-easy-rag-kotlin/src/test/kotlin/io/quarkiverse/sample/chatbot/SentimentAnalyzerTest.kt
Updated callback scheduling to return detailed error messages. Introduced session ID handling and secure WebSocket connections in the frontend. Enhanced logging, configuration management, and prompt guidance for clarity and improved user experience.
This PR replaces #1495
> Kotlin sample: Refactor chatbot for validation, session handling, and error logging

- samples/chatbot-easy-rag-kotlin/src/main/resources/application-dev.properties
- samples/chatbot-easy-rag-kotlin/src/main/resources/prompts/assistant-system-prompt.md
Kotlin sample: Prompt management and cleanup
> Kotlin sample: Prompt management and cleanup

- docs/modules/ROOT/pages/llms.adoc
> Document LLM access options

- samples/chatbot-easy-rag-kotlin/LINKS.md
- samples/chatbot-easy-rag-kotlin/README.md
- samples/chatbot-easy-rag-kotlin/pom.xml
- samples/chatbot-easy-rag-kotlin/src/main/kotlin/io/quarkiverse/langchain4j/sample/chatbot/ChatBotWebSocket.kt
Kotlin Chatbot Sample Improvements
- Remove `@SessionScoped` from `ChatBotWebSocket`.
- Added the `kotlin.compiler.release` property to align with the Java version specified in the project.
- Updated README and LINKS.md
> Kotlin Chatbot Sample Improvements

- integration-tests/pom.xml
- pom.xml
This is needed so the Quarkus Platform can
the extensions integration tests
> Generate test jars for integration tests

- docs/modules/ROOT/pages/easy-rag.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-easy-rag.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-easy-rag_quarkus.langchain4j.adoc
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagManualTriggerOnClasspathTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagNotRecursiveOnClasspathTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagNotRecursiveTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagOnClasspathTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagPathMatcherOnClasspathTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagReuseEmbeddingsDontAlreadyExistBaseTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagReuseEmbeddingsOnClasspathAlreadyExistTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagReuseEmbeddingsOnClasspathDontAlreadyExistTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagReuseEmbeddingsOnClasspathFileNotSetTest.java
- rag/easy-rag/deployment/src/test/java/io/quarkiverse/langchain4j/test/EasyRagWithExplicitAugmentorOnClasspathTest.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagConfig.java
- rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagIngestor.java
In the easy-rag extension the path you specify is currently a relative filesystem reference to the project. It would be nice if you could specify a relative reference to something on the classpath.
Fixes #1079
> Easy-rag - loading from classpath

- model-providers/google/gemini/ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/ai/gemini/deployment/AiGeminiProcessor.java
- model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiRecorder.java
- model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiRestApi.java
- model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiStreamingChatLanguageModel.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/BaseGeminiChatModel.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GeminiStreaminChatLanguageModel.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GeminiStreamingResponseBuilder.java
- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GenerateContentResponse.java
- model-providers/google/vertex-ai-gemini/deployment/src/main/java/io/quarkiverse/langchain4j/vertexai/gemini/deployment/VertexAiGeminiProcessor.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiRecorder.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiStreamingChatLanguageModel.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertxAiGeminiRestApi.java
> Add Gemini AI Streaming ChatModel

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/InProcessEmbeddingProcessor.java
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15-and-ollama/pom.xml
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15-and-ollama/src/main/java/org/acme/test/Resource.java
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15-and-ollama/src/main/resources/application.properties
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15-and-ollama/src/test/java/org/acme/test/ResourceTest.java
- integration-tests/in-process-embedding-models/pom.xml
> Make in-process embedding models respect select model provider

- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/fewshots/SentimentAiService.java
- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/fewshots/SentimentResource.java
- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/images/Endpoint.java
- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/images/EndpointGeneration.java
- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/images/ImageAiService.java
- docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/images/ImageGenerationAiService.java
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/guide-few-shots.adoc
- docs/modules/ROOT/pages/guide-generating-image.adoc
- docs/modules/ROOT/pages/guide-passing-image.adoc
Add:
- **Few-shots guide.**
- **Passing image guide.**
- **Generating image guide**
> Few-shots, and Image guides

- pom.xml
> Fix milvus dependency version

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java
> fix: dev-ui being stuck on error

- integration-tests/ai-gemini/pom.xml
- integration-tests/anthropic/pom.xml
- integration-tests/azure-openai/pom.xml
- integration-tests/devui-multiple-embedding-models/pom.xml
- integration-tests/devui/pom.xml
- integration-tests/easy-rag/pom.xml
- integration-tests/hugging-face/pom.xml
- integration-tests/in-process-embedding-models/embed-all-minilm-l6-v2-q/pom.xml
- integration-tests/in-process-embedding-models/embed-all-minilm-l6-v2/pom.xml
- integration-tests/in-process-embedding-models/embed-bge-small-en-q/pom.xml
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15-and-ollama/pom.xml
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15-q/pom.xml
- integration-tests/in-process-embedding-models/embed-bge-small-en-v15/pom.xml
- integration-tests/in-process-embedding-models/embed-bge-small-en/pom.xml
- integration-tests/in-process-embedding-models/embed-e5-small-v2-q/pom.xml
- integration-tests/in-process-embedding-models/embed-e5-small-v2/pom.xml
- integration-tests/jlama/pom.xml
- integration-tests/llama3-java/pom.xml
- integration-tests/mcp/pom.xml
- integration-tests/mistralai/pom.xml
- integration-tests/multiple-providers/pom.xml
- integration-tests/ollama/pom.xml
- integration-tests/openai/pom.xml
- integration-tests/rag-pgvector-flyway/pom.xml
- integration-tests/rag-pgvector/pom.xml
- integration-tests/rag/pom.xml
- integration-tests/simple-ollama/pom.xml
- integration-tests/tools/pom.xml
- integration-tests/vertex-ai-gemini/pom.xml
This allows to use the tests with productized versions of the extension (and Quarkus)
> Add ability to run integration tests with another version of the extension

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
- core/deployment/src/test/java/io/quarkiverse/langchain4j/test/toolresolution/MaxSequentialToolExecutionsTest.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusAiServicesFactory.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DeclarativeAiServiceCreateInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1676
> Allow setting maxSequentialToolInvocations on the RegisterAiService annotation

- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiChatLanguageModel.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiEmbeddingModel.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiRecorder.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiStreamingChatLanguageModel.java
- model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/config/LangChain4jVertexAiGeminiConfig.java
- model-providers/google/vertex-ai/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/VertexAiChatLanguageModel.java
- model-providers/google/vertex-ai/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/VertexAiRecorder.java
- model-providers/google/vertex-ai/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/config/LangChain4jVertexAiConfig.java
- model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
- model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/LangChain4jAzureOpenAiConfig.java
- model-providers/openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorderEndpointTests.java
> Feature: Add proxy support for Azure OpenAI and Vertex and Google Gemini

- model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GenerateContentResponseHandler.java
@geoand Prevent NPE. 
I hope this covers all :smiley:
> Prevent NPE

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp_quarkus.langchain4j.adoc
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpClientRuntimeConfig.java
> Add the cacheToolList property for MCP clients

- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpPromptsStdioTransportTest.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpResourcesStdioTransportTest.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpServerHelper.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpToolsStdioTransportTest.java
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1749
@geoand We will need a 1.1.4 release and an update of the platform to get the CI working.
I will prepare a separate PR for `main` in a bit because there are conflicts
> [1.1] Fix MCP integration tests in the Platform CI

- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/http/QuarkusStreamableHttpMcpTransport.java
> Add Content-Type: application/json header to Streamable HTTP MCP client

- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpPromptsStdioTransportTest.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpResourcesAsToolsStdioTransportTest.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpResourcesStdioTransportTest.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpServerHelper.java
- integration-tests/mcp/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpToolsStdioTransportTest.java
Port of https://github.com/quarkiverse/quarkus-langchain4j/pull/1750 to `main`
> [main] Fix MCP integration tests in the Platform CI

- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
- core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
- model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
> Introduce support for ChatMemoryAccess

- model-providers/bedrock/runtime/src/main/java/io/quarkiverse/langchain4j/bedrock/runtime/jaxrsclient/JaxRsSdkHttpClientExecutable.java
Include response body in ClientWebApplicationException messages instead of only status info. This makes it easier to debug AWS service errors (e.g. Bedrock) where useful details are returned in the response body.
- add safe readErrorBody(Response) helper
- close response after reading entity
- include body text in exception message
> Propagate AWS error body in exceptions from AWS Bedrock

- model-providers/anthropic/runtime/src/main/java/io/quarkiverse/langchain4j/anthropic/runtime/AnthropicRecorder.java
- model-providers/anthropic/runtime/src/main/java/io/quarkiverse/langchain4j/anthropic/runtime/config/ChatModelConfig.java
> Disable TopK in Anthropic module when thinking is enabled

- samples/movie-similarity-search/pom.xml
- samples/movie-similarity-search/src/test/java/io/quarkiverse/langchain4j/sample/tests/MovieIT.java
- samples/movie-similarity-search/src/test/java/io/quarkiverse/langchain4j/sample/tests/MovieTest.java
- samples/pom.xml
- Change pom to allow depending on the platform BOM
- Add tests to the module
- Add the module into parent `samples` module
Native tests are disabled due to https://github.com/quarkiverse/quarkus-langchain4j/issues/1814
> Add tests for movie-search sample

- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
This matches same behavior as langchain4j
> Add tool result messages to chat memory after tool calls

- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp.adoc
- docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp_quarkus.langchain4j.adoc
- mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpProcessor.java
- mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/registryclient/McpRegistryClientTest.java
- mcp/runtime/pom.xml
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRegistryClientName.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpBuildTimeConfiguration.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpRegistryClientRuntimeConfig.java
- mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpRuntimeConfiguration.java
> MCP registry client integration

- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/AuditSourceInfo.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/InitialMessagesCreatedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/LLMInteractionCompleteEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/LLMInteractionEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/LLMInteractionFailureEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/ResponseFromLLMReceivedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/ToolExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/guardrails/GuardrailExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/guardrails/InputGuardrailExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/guardrails/OutputGuardrailExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/guardrails/internal/DefaultInputGuardrailExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/guardrails/internal/DefaultOutputGuardrailExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/internal/DefaultInitialMessagesCreatedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/internal/DefaultLLMInteractionCompleteEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/internal/DefaultLLMInteractionFailureEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/internal/DefaultResponseFromLLMReceivedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/audit/internal/DefaultToolExecutedEvent.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
- core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AuditSourceInfoImpl.java
- docs/modules/ROOT/pages/observability.adoc
> Deprecate existing auditing events.
