quarkiverse/quarkus-langchain4j

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/Langchain4jDotNames.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/MyAiService.java
docs/modules/ROOT/pages/agent-and-tools.adoc
docs/modules/ROOT/pages/ai-services.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/retrievers.adoc
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/BeanDeclarativeAiServicesTest.java
samples/chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/Bot.java
samples/email-a-poem/src/main/java/io/quarkiverse/langchain4j/sample/MyAiService.java
samples/fraud-detection/src/main/java/io/quarkiverse/langchain4j/sample/FraudDetectionAi.java
samples/review-triage/src/main/resources/META-INF/resources/index.html

Remove the need to explicitly configure retriever and memory beans for @RegisterAiService

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java

Ignore known annotations in parameter binding

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/AiServiceWithToolsAndNoMemoryTest.java

Fail at build time when tools set and no memory provided

---

.github/workflows/build-nightly.yml
.github/workflows/build-pull-request.yml
.github/workflows/build-push.yml
pinecone/deployment/src/test/java/io/quarkiverse/langchain4j/pinecone/deployment/PineconeEmbeddingStoreTest.java

- split the workflow for pull_request/push to two workflows, where the one for 'push' (to main) doesn't include Pinecone tests
- introduce a new nightly workflow that runs Pinecone tests
- add a few more logging statements to make the Pinecone test troubleshooting easier in case all else fails

Attempt to make CI run Pinecone tests more reliably

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RemovableChatMemoryProvider.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DeclarativeAiServiceBeanDestroyer.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceContext.java
docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/ChatMemoryBean.java
docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/MySmallMemoryProvider.java
docs/modules/ROOT/pages/agent-and-tools.adoc
docs/modules/ROOT/pages/ai-services.adoc
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AuditingServiceTest.java
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/RemovableChatMemoryTest.java
samples/chatbot/pom.xml
samples/chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/Bot.java
samples/chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/ChatBotWebSocket.java
samples/csv-chatbot/pom.xml
samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/ChatBotWebSocket.java
samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/MovieMuse.java
samples/email-a-poem/src/main/java/io/quarkiverse/langchain4j/sample/ChatMemoryBean.java

This is done because otherwise the chat memory
does not get cleared properly.
Fixes: #95
Do we need a docs update to go along with this?

Make @RegisterAiService beans request scoped by default

---

openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java

For some reason when using the 'demo' key,
the response comes back as type text/html
but the content is still JSON

Make the `demo` OpenAI key usable

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
integration-tests/openai/src/test/java/org/acme/example/openai/aiservices/AssistantResourceWithMetricsTest.java

We now use tags in order to reduce
the number of keys
- Closes: #143

Restructure recorded metrics

---

pom.xml

This is needed because Langchain4j
used POI 5.2.3 which requires the
substitution present in version 2.0.4
of the extension in order to work
on Mac

Use previous version of POI extension

---

.sdkmanrc
core/runtime/pom.xml

Also add a .sdkmanrc in passing.

Get rid of warning by removing duplicate micrometer dependency

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/Langchain4jDevUIProcessor.java

- don't cause NPE if `ToolsMetadataBuildItem` is null
- properly show the tool's name if it's not the same as the method name

Minor Dev UI fixes for tools

---

redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStore.java

This tries to detect that the application stores embeddings with a different vector size than the one that was declared when creating the Redis index. Shows a warning (only once).
This is only done if Quarkus created the index automatically, otherwise we don't dare guess how exactly the index is configured.
If this makes sense, I can do the same for other stores too.

Warn about dimension mismatch

---

openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java
openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/JsonParsingTest.java

The previous way they were declared meant
that they would affect other REST Clients
too.
- Fixes: #164

Limit scope of OpenAiRestApi providers

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/Langchain4jDevUIProcessor.java
core/deployment/src/main/resources/dev-ui/qwc-chat.js
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java

Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/195
Adds a page for chatting when there's a chat model available .
It assumes that only one chat model registered in CDI is allowed, and that a single chat memory provider will also be always available (are these assumptions ok?)
It allows to have a conversation utilizing a memory and then click a button to restart, dropping the memory

Dev UI chatting capability

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
integration-tests/openai/src/main/java/org/acme/example/openai/QuarkusRestApiResource.java
openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java
openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiClient.java
openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/OpenAiRestApiSmokeTest.java
openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/WiremockUtils.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/Langchain4jOpenAiConfig.java

See https://platform.openai.com/docs/api-reference/organization-optional - allow the organizationId to be specified in the configuration.
Fixes #131

Allow specifying the organizationId in the configuration

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/EmbeddingModelConfig.java

This fixes a regression that appeared with `0.5.1` , the OpenAI Embedding request is failing because an user with `null` value was passed to the request. 
This add the `user` property , I added a default value because that was the only way to get the request passed.

Adding the user config property for openai embedding model

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/Langchain4jDotNames.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DeclarativeAiServiceCreateInfo.java
docs/modules/ROOT/pages/retrievers.adoc
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
samples/chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/Bot.java
samples/csv-chatbot/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/MovieMuse.java

With this change a retriever is no longer
added by default to an AiService,
but needs to be configured explicitly.
- Closes: #184

Refactor retriever use in `@RegisterAiService`

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java

Provides a slightly more meaningful exception that includes the name of the tool that was not found.
Fixes: #253

Throw a more meaningful exception instead of NPE when tool is not found

---

openai/azure-openai/runtime/pom.xml
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiChatModel.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiEmbeddingModel.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/Langchain4jAzureOpenAiConfig.java
openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorderEndpointTests.java

Refactor Azure endpoint properties and how the baseUrl is computed.
See [this issue comment](https://github.com/quarkiverse/quarkus-langchain4j/issues/248#issuecomment-1912207740).
Fixes #248

Fix Azure endpoint properties and baseUrl computation

---

integration-tests/openai/src/main/java/org/acme/example/openai/QuarkusRestApiResource.java
openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java
openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiClient.java
openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/OpenAiRestApiSmokeTest.java

Only send the `Authorization` header for OpenAI requests and only send the `api-key` header on Azure OpenAI requests.
- Fixes #264

Only pass Authorization/api-key headers when necessary

---

samples/chatbot/pom.xml
samples/csv-chatbot/pom.xml
samples/email-a-poem/pom.xml
samples/fraud-detection/pom.xml
samples/review-triage/pom.xml

I've seen some failures (during a parallel build) due to wrong build order - the `parent.relativePath` of samples has to point at an exact pom.xml, otherwise it doesn't make sure that all extensions are built before samples

Ensure correct build order (samples AFTER extensions)

---

docs/modules/ROOT/pages/prompt-engineering.adoc

Hi,
This is a small edit to include a hint in a `prompt-engineering.adoc` guide for devs to ask for a valid, unwrapped JSON when working with DTO classes.
I was working with the following AI service:
```java
@ApplicationScoped
@RegisterAiService
public interface Translator {
@SystemMessage("""
You are a professional translator.
You translate provided text lines from a source language to a target language. 
Objective: Translate provided text lines from {sourceLang} to {targetLang}.
""")
@Timeout(value = 2, unit = MINUTES)
Translation translate(String sourceLang, String targetLang, @UserMessage String texts);
public static @Data class Translation {
private List<String> translatedTextLines;
}
}
```
To my surprise, it didn't work as intended and I was getting HTTP 500 when requesting my …

Note about asking for valid and unwrapped JSON

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java

Otherwise it fails when `ChatMemoryProvider` is a request-scoped bean

Activate the request context in ChatJsonRPCService

---

core/runtime/pom.xml
hugging-face/runtime/pom.xml
milvus/deployment/pom.xml
milvus/runtime/pom.xml
openai/openai-common/runtime/pom.xml
pom.xml

- Closes https://github.com/quarkiverse/quarkus-langchain4j/pull/252
- Closes https://github.com/quarkiverse/quarkus-langchain4j/pull/215
Unlike the other PRs, this doesn't require any maintenance when introducing a new module. 
For reference, this plugin is also used in https://github.com/smallrye/smallrye-common/blob/main/pom.xml#L203 and https://github.com/smallrye/smallrye-reactive-messaging/blob/main/pom.xml#L609

Introduce quarkus-langchain4j-bom

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ResponseFormatMixin.java
openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/jackson/ResponseFormatTypeMixin.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ChatModelConfig.java
samples/review-triage/src/main/resources/application.properties

- Resolves #274
Not sure about a couple of things:
* tests: I looked into enriching the ITs but didn't find anything meaningful to assert...
* response format type: currently I went with a String. Langchain4J uses an enum `ResponseFormatType`. Not sure if I should surface the langchain4j enum to let langchain4j handle the maintenance :) Or use a new enum for this project? Let me know what you prefer.

Add support for OpenAI response format

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/ChatMessageSerializerTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/ContextMixin.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/ImageBuilderMixin.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/ImageContentMixin.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/ImageMixin.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/TextContentDeserializer.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/TextContentMixin.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/ToolExecutionResultMessageMixin.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/UserMessageDeserializer.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/jackson/UserMessageMixin.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-chroma.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-huggingface.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-pgvector.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-pinecone.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-redis.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j.adoc
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java
pom.xml

In the future we'll also have to transition to using `retrievalAugmentor` instead of `retriever` in `@RegisterAiService`, but let's not hold up a new release for that

Bump to LangChain4j 0.27.1

---

chroma/deployment/pom.xml
chroma/deployment/src/test/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaEmbeddingStoreCDITest.java
chroma/deployment/src/test/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaEmbeddingStoreTest.java
chroma/runtime/src/main/java/io/quarkiverse/langchain4j/chroma/ChromaEmbeddingStore.java
chroma/runtime/src/main/java/io/quarkiverse/langchain4j/chroma/runtime/ChromaCollectionsRestApi.java
chroma/runtime/src/main/java/io/quarkiverse/langchain4j/chroma/runtime/DeleteEmbeddingsRequest.java
infinispan/deployment/pom.xml
infinispan/deployment/src/test/java/io/quarkiverse/langchain4j/infinispan/deployment/InfinispanEmbeddingStoreTest.java
milvus/deployment/pom.xml
milvus/deployment/src/test/java/io/quarkiverse/langchain4j/milvus/deployment/MilvusEmbeddingStoreTest.java
pgvector/deployment/pom.xml
pgvector/deployment/src/test/java/io/quarkiverse/langchain4j/pgvector/test/Langchain4jPgvectorTest.java
pinecone/deployment/pom.xml
pinecone/deployment/src/test/java/io/quarkiverse/langchain4j/pinecone/deployment/PineconeEmbeddingStoreTest.java
redis/deployment/pom.xml
redis/deployment/src/test/java/io/quarkiverse/langchain4j/redis/deployment/RedisEmbeddingStoreTest.java
samples/fraud-detection/src/main/resources/application.properties

Reuse the `EmbeddingStoreIT` class that kinda serves as a TCK for embedding stores.
This removes a lot of code duplication and brings us a bit closer to the upstream langchain4j project.
I also had to add the `deleteAll` functionality for the Chroma store, because the testcase requires that each test starts with a clean store.

Unify on using EmbeddingStoreIT as test base for embedding stores

---

openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiClient.java

The previous hack will no longer work in Quarkus 3.9

Future-proof setting the User-Agent header

---

openai/openai-vanilla/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/devui/OpenAiDevUIProcessor.java
openai/openai-vanilla/deployment/src/main/resources/dev-ui/qwc-images.js
openai/openai-vanilla/deployment/src/main/resources/dev-ui/qwc-moderation.js
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/devui/OpenAiImagesJsonRPCService.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/devui/OpenAiModerationModelsJsonRPCService.java

- Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/322 : for the moderation and image pages, when using the default model and the API key is missing, we show a nicer error now. For other pages, it's not necessary because they inject the model directly from CDI and thus if the API key is missing, it will have failed earlier anyway.
- Moderation and image pages now support selecting the named OpenAI model configuration, which will serve as the "base", on top of which you can override parameters using dropdowns
- I'd like to extend the embedding store and chat pages to support multiple models too, but haven't figured out yet how to do it nicely, will revisit
CC @gastaldi

Adapt OpenAI Dev UI pages to multiple models

---

.github/workflows/build-against-langchain4j.yml
README.md
bam/runtime/src/main/resources/META-INF/quarkus-extension.yaml
chroma/runtime/src/main/resources/META-INF/quarkus-extension.yaml
core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
hugging-face/runtime/src/main/resources/META-INF/quarkus-extension.yaml
infinispan/runtime/src/main/resources/META-INF/quarkus-extension.yaml
milvus/runtime/src/main/resources/META-INF/quarkus-extension.yaml
ollama/runtime/src/main/resources/META-INF/quarkus-extension.yaml
openai/azure-openai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
openai/openai-common/runtime/src/main/resources/META-INF/quarkus-extension.yaml
openai/openai-vanilla/runtime/src/main/resources/META-INF/quarkus-extension.yaml
openshift-ai/runtime/src/main/resources/META-INF/quarkus-extension.yaml
pgvector/runtime/src/main/resources/META-INF/quarkus-extension.yaml
pinecone/runtime/src/main/resources/META-INF/quarkus-extension.yaml
redis/runtime/src/main/resources/META-INF/quarkus-extension.yaml
watsonx/runtime/src/main/resources/META-INF/quarkus-extension.yaml

I notice that https://quarkus.io/extensions/io.quarkiverse.langchain4j/quarkus-langchain4j-azure-openai/ (and others) refers to 'Langchain4j' but https://github.com/langchain4j/langchain4j calls it 'LangChain4j'. 
We should probably be consistent, so I've updated the metadata. Our `pom.xml`s already use 'LangChain4j', so I didn't need to change those. 
All of the Java code uses `Langchain4j`, but changing that is more invasive, and could affect external APIs, so I've left it alone for now.

Update extension metadata to use name consistent with LangChain4j

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DocumentNativeSupportProcessor.java

The original issue was reported [here](https://github.com/quarkiverse/quarkiverse/issues/195#issuecomment-2033751433) and the cause is:
```
2024-04-03T07:24:56.6850640Z Error: Class initialization of dev.langchain4j.rag.query.transformer.CompressingQueryTransformer failed. Use the option 
2024-04-03T07:24:56.6852035Z 
2024-04-03T07:24:56.6853053Z     '--initialize-at-run-time=dev.langchain4j.rag.query.transformer.CompressingQueryTransformer'
2024-04-03T07:24:56.6854029Z 
2024-04-03T07:24:56.6854439Z  to explicitly request initialization of this class at run time.
2024-04-03T07:24:56.6856584Z com.oracle.svm.core.util.UserError$UserException: Class initialization of dev.langchain4j.rag.query.transformer.CompressingQueryTransformer failed. Use the option 
2024-04-03T07:24:56.6858295Z …
```

Fix native compilation issue for csv-chatbot sample

---

openai/azure-openai/deployment/src/test/java/io/quarkiverse/langchain4j/azure/openai/test/AzureOpenAiChatLanguageModelSmokeTest.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiImageModel.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/Consts.java

- Add the user agent to `AzureOpenAiImageModel.java` as it was missing
- Create a specific user agent for Quarkus-LangChain4J : the issue with the currently used one is that it's the same as the LangChain4J Azure OpenAI project, which underneath uses the official Azure SDK. I'm trying to separate both, as for reporting I want to know who uses our SDK and who doesn't, so we know where we need to put the effort.

Fix Azure OpenAI user agent

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/InProcessEmbeddingProcessor.java
integration-tests/multiple-providers/pom.xml
integration-tests/multiple-providers/src/main/resources/application.properties
integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleEmbeddingModelsTest.java

Add qualifier to InProcessEmbeddingStore when needed 2

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/MethodUtil.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/deployment/MethodUtilTest.java

Fix duplicate method exception when registering ai services

---

docs/pom.xml
docs/src/test/java/io/quarkiverse/langchain4j/docs/it/AntoraTest.java

fixing https://github.com/quarkiverse/quarkus-langchain4j/issues/493 and what is [related failures](https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/langchain4j.20build.20troubles) like missing classes in test and conflicting 8081 ports.
by removing antora all builds works again on OSX/podman.
My theory is that the antora devservice is assuming volume mounts/permissions can be adjusted from inside container in a portable way - it can't (unfortunately).
Thus it fails somewhat silently - causing the AntoraTest to not shutdown, causing 8081 failures ...why it then result in devui not being able to find classes is beyond me - but that error goes away with this code commented out.

disable antora until having proper working solution

---

anthropic/runtime/src/main/java/io/quarkiverse/langchain4j/anthropic/runtime/config/ChatModelConfig.java
cohere/runtime/src/main/java/io/quarkiverse/langchain4j/cohere/runtime/QuarkusCohereScoringModel.java
cohere/runtime/src/main/java/io/quarkiverse/langchain4j/cohere/runtime/config/CohereScoringModelConfig.java
docs/modules/ROOT/pages/includes/quarkus-langchain4j-anthropic.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-cohere.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiChatModel.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiEmbeddingModel.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/LangChain4jAzureOpenAiConfig.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiImageModel.java
openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/LangChain4jOpenAiConfig.java

I've also added some basic validation checks where possible (models that are implemented on our side), but I'm not completely sure about this. We could potentially do that in the recorders, making it more like validating the configuration?!

Turn off built-in fault tolerance by default

---

mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/QuarkusMistralAiClient.java

fix #489 
@geoand as discuss, the PR to fix the NPE in case of no data in `content` field in Mistral response.
I didn't find tests in Mistral package but I tested on my project and it fixes the bug.
Let me know if I need to write a test somewhere 😉

fix: 🐛 fix NPE if chunk is null for Mistral AI

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-watsonx.adoc
watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/EmbeddingModelBuildConfig.java
watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/LangChain4jWatsonBuildConfig.java
watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/WatsonxProcessor.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AiChatServiceTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AiEmbeddingTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AllPropertiesTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/CacheTokenTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/DefaultPropertiesTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/HttpErrorTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/WireMockUtil.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxEmbeddingModel.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxModel.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/EmbeddingRequest.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/EmbeddingResponse.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/IAMError.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/IdentityTokenRequest.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/WatsonxError.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/client/WatsonxRestApi.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/exception/WatsonxException.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ChatModelConfig.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/EmbeddingModelConfig.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/LangChain4jWatsonxConfig.java
watsonx/runtime/src/test/java/io/quarkiverse/langchain4j/watsonx/runtime/DisabledModelsWatsonRecorderTest.java

Enable embedding api in watsonx.ai module.
- Closes: #494

Enable Embedding API in watsonx.ai

---

integration-tests/ollama/src/main/java/org/acme/example/openai/chat/ollama/ChatLanguageModelResource.java
ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaProcessor.java
ollama/runtime/pom.xml
ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/CompletionResponse.java
ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaClient.java
ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java
ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java
ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/OllamaRecorder.java

PR to try to add the streaming feature to Ollama provider through the extension 😉 
First commits are the setup of the the feature 🏗️.
- Closes: #501

feat: ✨ ollama streaming mode

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-watsonx.adoc
docs/modules/ROOT/pages/watsonx.adoc
watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatModelBuildConfig.java
watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/EmbeddingModelBuildConfig.java
watsonx/deployment/src/main/java/io/quarkiverse/langchain4j/watsonx/deployment/LangChain4jWatsonBuildConfig.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AllPropertiesTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/DefaultPropertiesTest.java
watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/WireMockUtil.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxModel.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxStreamingChatModel.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/Parameters.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ChatModelConfig.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/EmbeddingModelConfig.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/IAMConfig.java
watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/LangChain4jWatsonxConfig.java

The following parameters have been added to the `ChatLanguageModel` and `StreamingChatLanguageModel`:
- `quarkus.langchain4j.watsonx.chat-model.length-penalty.decay-factor`
- `quarkus.langchain4j.watsonx.chat-model.length-penalty.start-index`
- `quarkus.langchain4j.watsonx.chat-model.include-stop-sequence`
- `quarkus.langchain4j.watsonx.chat-model.truncate-input-tokens`
I also used this PR to add some links to the watsonx.ai documentation.

Add new parameters to the watsonx.ai chat model

---

vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiRecorder.java

The path has to be the same as in `LangChain4jVertexAiGeminiConfig`
- Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/555

Fix configuration error in Gemini

---

docs/pom.xml
docs/src/test/java/io/quarkiverse/langchain4j/docs/it/AntoraTest.java
pom.xml

@jmartisk could you please give this a try?

Upgrade to Quarkus Antora 0.0.4 - fix podman issues

---

samples/email-a-poem/README.md

A lot of people that will go through the email me a poem read me, won't even know what `podman` is.
So, this pull request uses `docker` first and then includes instructions for `podman` users.

Include instruction for docker users in email-me-a-poem readme

---

samples/email-a-poem/src/main/resources/META-INF/resources/index.html

As discussed in #564 the UI is a bit confusing, as the textarea used for showing the response implies that the user is supposed to add something there.
This PR changes the texteara, with a span (which is invisible by default) and it populates it with the response when available. It also adds a `Working...` message when the button is pressed to further improve the experience.

Improve email-me-a-poem ui

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
websockets-next/tests/src/test/java/io/quarkiverse/langchain4j/websockets/next/tests/WebSocketsNextTest.java

This is done by adding the name of the interface and method to the name given by the provider

Segregate memory of concurrent requests to different AI services

---

samples/jbang-joke-bot/README.md
samples/jbang-joke-bot/jokes.java

The pull request changes the jbang jokes bot, to be a cli application  instead of a web application.
The reasoning is that we already have a lot of samples going the web path and it seems to me like a missed opportunity to show case to also demonstrate how it can be done in the CLI.
Now, I understand that the reasoning might be to implement something with the fewer lines of code possible, but I argue that the code is hard to understand.

Refactor jokes jbang bot to be picocli based

---

openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java

Fixes wrong configuration being passed while initializing Azure Embeddings client.

Properly configure for embedding model

---

.github/workflows/release.yml

Fix update sample version when releasing

---

openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ChatModelConfig.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/EmbeddingModelConfig.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ImageModelConfig.java
openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/LangChain4jAzureOpenAiConfig.java
openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorderEndpointTests.java

Relevant to #237, this will allow overriding the following properties per model in the Azure OpenAI configuration
- `endpoint`
- `resource-name`
- `deployment-name`
Example configuration that is now possible:
```properties
quarkus.langchain4j.azure-openai.ad-token=token
quarkus.langchain4j.azure-openai.api-version=2023-07-01-preview
quarkus.langchain4j.azure-openai.chat-model.enabled=true
quarkus.langchain4j.azure-openai.deployment-name=my-deployment-name
quarkus.langchain4j.azure-openai.embedding-model.enabled=true
quarkus.langchain4j.azure-openai.resource-name=name
quarkus.langchain4j.azure-openai.embedding-model.deployment-name=another-deployment-name
```
In ht e above example, all models in the parent configuration will have the `my-deployment-name`, but the Embedding model will have …

Allow multi-deployment configuration for Azure OpenAI

---

model-providers/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiRecorder.java
model-providers/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/config/ChatModelConfig.java
model-providers/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/config/LangChain4jVertexAiGeminiConfig.java

and inherit the default from quarkus.langchain4j.timeout
- Closes:  https://github.com/quarkiverse/quarkus-langchain4j/issues/638

make vertexai.gemini timeout configurable

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/LangChain4jDevUIProcessor.java
model-providers/openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/PromptDevModeTest.java
model-providers/openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/Resource.java
model-providers/openai/openai-vanilla/devmode-tests/src/test/java/io/quarkiverse/langchain4j/openai/test/ServiceWithResource.java
model-providers/openai/openai-vanilla/devmode-tests/src/test/resources/cs-organizer.txt
testing-internal/src/main/java/io/quarkiverse/langchain4j/testing/internal/WiremockAware.java

Relates to: https://github.com/quarkiverse/quarkus-langchain4j/issues/618#issuecomment-2136790375

Watch files configured in `@SystemMessage` or `@UserMessage`

---

core/deployment/src/test/java/io/quarkiverse/langchain4j/test/JsonTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java

Ollama Illegal unquoted character

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/AdditionalDevUiCardBuildItem.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/LangChain4jDevUIProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/OpenWebUIDevUIProcessor.java
core/deployment/src/main/resources/dev-ui/qwc-open-webui.js
core/runtime/pom.xml
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/OpenWebUIJsonRPCService.java
model-providers/ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/devui/OllamaDevUiProcessor.java
model-providers/openai/openai-common/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/devui/OpenAiDevUIProcessor.java

Resolves: #581 
The pull request introduces the following:
- A new Open WebUI card under langchain4j extension (when using OpenAI or Ollama).
- The Open WebUI card allows starting, stoping or launching Open WebUI.
- OpenAI api key is automatically passed to the container (for OpenAI)
- Ollama base url is automatically passed to the container (for Ollama)
- Options for custom env variables, env variable mapping and port bindings are provided. 
- Added support for automatically signing up

Allow creating and launching an OpenWebUI container via Dev UI 

---

core/deployment/src/main/resources/dev-ui/qwc-chat.js
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java

The pull request introduces a new option (streaming chat). The option is enabled when model supports streaming chat model and rag is disabled (streaming chat can't work with rag atm). When user enables streaming chat. Responses from the model are streamed to the devui chat screen.
- Resolves: #442

Support streaming in dev-ui chat

---

samples/chatbot-easy-rag/src/main/resources/application.properties
samples/chatbot/src/main/resources/application.properties
samples/cli-translator/src/main/resources/application.properties
samples/review-triage/src/main/resources/application.properties
samples/sql-chatbot/src/main/resources/application.properties

This make it easier when switching from one
model provider to another

Use top-level timeout property in samples

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java

I've seen gpt-4o return these, so let's handle them without causing users headaches

Remove preceding  and trailing json markers when converting from json

---

embedding-stores/chroma/deployment/src/test/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaEmbeddingStoreCDITest.java
embedding-stores/chroma/deployment/src/test/java/io/quarkiverse/langchain4j/chroma/deployment/ChromaEmbeddingStoreTest.java
samples/email-a-poem/README.md
samples/email-a-poem/pom.xml
samples/email-a-poem/src/main/java/io/quarkiverse/langchain4j/sample/MyAiService.java
samples/email-a-poem/src/main/resources/application.properties

The following changes have been made:
* Use quarkus-mailpit
- This is done to make the setup simpler
* Introduce the LGTM observability Dev Service
- This is done so users don't have to start anything manually
- For this to work, users need to use -Dobservability
* Use gpt-4o
- This is done because GTP-3.x can sometimes result in multiple tool invocations
- Improve the prompt to ensure that no markers are added
* Update README accordingly

Update the email me a poem sample

---

core/deployment/src/main/resources/dev-ui/qwc-chat.js
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java

Dev UI: Allow RAG and tools together with streaming

---

.github/workflows/build-against-langchain4j.yml

to override the `langchain4j.version` to the correct snapshot that was just built from the langchain4j repository
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/701

Fix the nightly job

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/PromptProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/config/LangChain4jBuildConfig.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/ResponseSchemaUtil.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
docs/modules/ROOT/pages/ai-services.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j.adoc
model-providers/bam/deployment/src/test/java/io/quarkiverse/langchain4j/bam/deployment/ResponseSchemaExceptionTest.java
model-providers/bam/deployment/src/test/java/io/quarkiverse/langchain4j/bam/deployment/ResponseSchemaOffTest.java
model-providers/bam/deployment/src/test/java/io/quarkiverse/langchain4j/bam/deployment/ResponseSchemaOnTest.java

As mentioned in #679, the idea of this PR is to increase the flexibility of prompt creation with the use of the `{response_schema}` placeholder.
This new placeholder allows the developer to choose where to place the schema in the prompt.
```java
@RegisterAiService
public interface LLMExtractor {
@UserMessage("""
<|begin_of_text|><|start_header_id|>system<|end_header_id|>
You are a entity extractor. You take input and output a JSON.
Your goal is to:
* Extract the entities from the text: ["firstname", "lastname", "email", "city"];
* Respond only with the entities extracted from the text;
* Capitalize the first letter of the firstname, lastname, and city entities;
* {response_schema};
<|eot_id|>
<|start_header_id|>user<|end_header_id|>
INPUT: {text} …
```

Allow the use of the {response_schema} in the prompt

---

model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ChatModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/EmbeddingModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ImageModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/LangChain4jAzureOpenAiConfig.java
model-providers/openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorderEndpointTests.java

Add domain config for Azure AI

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/auth/ModelAuthProvider.java
docs/modules/ROOT/pages/openai.adoc
model-providers/openai/openai-common/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/OpenAiCommonProcessor.java
model-providers/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/OpenAiRestApi.java
model-providers/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiClient.java

- Moving the authentication interface from Azure OpenAI introduced in #646 to the Quarkus Langchain Core so that it can be reused across other model providers
- Making Azure OpenAI use this.
Implementation of request mentioned in #626

Putting Generic Authentication flow to the Core

---

docs/modules/ROOT/pages/pgvector-store.adoc

Line 7 - replace reference to "Redis" with reference to "PostgreSQL pgVector" as this page deals with Postgres and pgVector.

Update pgvector-store.adoc - remove reference to Redis

---

embedding-stores/neo4j/deployment/src/test/java/io/quarkiverse/langchain4j/neo4j/Neo4jEmbeddingStoreTest.java

Quick workaround for the failing `Neo4jEmbeddingStoreTest`
see https://github.com/quarkiverse/quarkus-langchain4j/pull/713#issuecomment-2202704051

Hardcode neo4j image version to 5.20.0 for the tests for now

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java

Without this warning, users can end up with only an
error complaining about a duplicate null key
This was prompted by https://stackoverflow.com/q/78695273/2504224, but it's 
far from the first time I've seen the same issue.

Add a warning about missing -parameters flag for javac

---

model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/Consts.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ChatModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ConfigConstants.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/EmbeddingModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ImageModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/LangChain4jAzureOpenAiConfig.java

Addition to #698, this brings the `domainName()` configuration property to feature parity with similar properties, like deploymentName.

Bringing domain-name on par with the rest of the optional configurations

---

core/deployment/src/main/resources/dev-ui/qwc-embedding-store.js

Show the whole table with search results. This seems to prevent the table from disappearing after I zoom in in the browser - which was utterly annoying during demos.

Improve UI of the embedding store page

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java

This could happen before when there were no template params

Prevent false positive of javac -parameters

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ChatModelConfig.java

As specified [here](https://platform.openai.com/docs/api-reference/chat/create#chat-create-stop) in a chat completion request we should be able to pass a `stop` parameter containing a string or list of strings.
It's implemented in upstream `langchain4j` , this PR just add it to the config and the recorder.

add stop sequence config for openAI chat config model

---

docs/modules/ROOT/pages/ai-services.adoc

After PR #372, the `@RegisterAiService(moderationModelSupplier = RegisterAiService.BeanModerationModelSupplier.class)`
is no longer necessary.

Fix Moderation doc

---

integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleTokenCountEstimatorProvidersTest.java
model-providers/bam/runtime/src/main/java/io/quarkiverse/langchain4j/bam/runtime/BamRecorder.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java

Essentially the ChatLanguageModel was being
built too early thus messing up the construction
order of the dependencies
- Fixes: #731

Fix issue with Azure OpenAI and metrics usage

---

model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/Role.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/jackson/RoleSerializer.java

Ollama Role serialization in lower case, fix issue with Ollama 0.2.5
Fix: https://github.com/quarkiverse/quarkus-langchain4j/issues/743

Ollama Role serialization in lower case, fix issue with Ollama 0.2.5

---

model-providers/hugging-face/runtime/src/main/java/io/quarkiverse/langchain4j/huggingface/runtime/HuggingFaceRecorder.java
model-providers/hugging-face/runtime/src/main/java/io/quarkiverse/langchain4j/huggingface/runtime/config/ChatModelConfig.java

Fixed issue returning the full text by default for hugging face

Set `false` as default value for fullText in hugging face config

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-watsonx.adoc
docs/modules/ROOT/pages/watsonx.adoc
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AiChatServiceTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/DefaultPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/TokenCountEstimatorTest.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxStreamingChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ChatModelConfig.java

Before these changes, all `ChatMessage`(s) were joined using the delimiter `\n` or `\n\n`.
The idea is to give the choice to the developer by using the `quarkus.langchain4j.watsonx.chat-model.prompt-joiner` property.
This way the developer can choose the preferred way of concatenating messages to ensure the prompt is structured correctly.

Add `prompt-joiner` property for watsonx provider

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/CommittableChatMemory.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DefaultCommittableChatMemory.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/NoopChatMemory.java
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/CustomChatMemoryStoreTest.java
quarkus-integrations/websockets-next/tests/src/test/java/io/quarkiverse/langchain4j/websockets/next/tests/WebSocketsNextTest.java

This is done by only committing the messages to memory when the AiService completes successfully.
- Fixes: #748

Ensure that @Retry works properly with chat memory

---

model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/ChatModelConfig.java
samples/review-triage/src/main/resources/application.properties
samples/secure-fraud-detection/README.md

This is done as gpt-4o-mini is better than gpt-3.5-turbo in all aspects
See https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/ for more details

Make gpt-4o-mini the default OpenAI model

---

docs/modules/ROOT/examples/io/quarkiverse/langchain4j/samples/RetrievalAugmentorExample.java

This aligns with the rest of the examples in the documentation page. There might be a good reason as I'm not an expert but it felt odd to see singleton here. If there is no reason, better align tot he more accepted `ApplicationScoped` and be consistent with the rest of the examples in the doc page.

Replace Singleton with ApplicationScoped

---

model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AiChatServiceTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AiEmbeddingTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/AllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/CacheTokenTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/DefaultPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/HttpErrorTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/TokenCountEstimatorTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/WireMockUtil.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/TokenGenerator.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxEmbeddingModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxStreamingChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextGenerationResponse.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/client/WatsonxRestApi.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/client/filter/BearerTokenHeaderFactory.java

What I did:
- Improved tests;
- Removed the ObjectMapper from the WatsonxStreamingChatModel;
- Introduced ReactiveClientHeadersFactory to inject the bearer token;
Just a note, my idea was also to add more tests for the StreamingChatModel part, but I didn't do it for quarkusio/quarkus#26253.

Polish watsonx code

---

model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ChatRequest.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ChatResponse.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/Message.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/MessageMapper.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModel.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/Role.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/Tool.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ToolCall.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/jackson/ToolTypeDeserializer.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/jackson/ToolTypeSerializer.java

Ollama 0.3.0 now has official support for tools,
see https://ollama.com/blog/tool-support for more
details.
This PR brings in the basic support for getting
tools to work
- Closes: #305

Add initial Ollama support for tool invocation

---

embedding-stores/pgvector/deployment/src/main/java/io/quarkiverse/langchain4j/pgvector/deployment/PgVectorEmbeddingStoreProcessor.java

Our PgVectorEmbeddingStore extends the one from LangChain4j and when injecting, it's easy to choose the one from upstream and then you're stuck with injection errors that are a bit hard to figure out as everything looks fine.
Let's make it a bit easier as it doesn't cost us anything.

Also allow to inject PgVectorEmbeddingStore with upstream type

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java

A null can be converted to an empty string. It happened to me because I was testing a service passing a title and a description and the description was sometimes null.

Avoid NPE when converting template param value

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java

The error is thrown anyway and handled by the error handler. Logging here makes the error logged twice in your typical REST setup (and probably any setup).
Fixes #863

Do not log error in AiServiceMethodImplementationSupport

---

docs/pom.xml
docs/src/test/java/io/quarkiverse/langchain4j/docs/it/AntoraTest.java

This reverts commit 03c416042b12ca55d7c6843bc8501ba23f2def7f.
+ moves antora to a separate profile and use -Dantora to use it.
see https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/antora.20in.20quarkiverse.20or.20just.20langchain4j.20when.20using.20podma.3F for discussion.
in short - podman can't run antora so at least me and @cescoffier can't build langchain without removing the docs build.
Thus i suggest to make antora a profile flag to enable.
relates to:
https://github.com/quarkiverse/quarkus-langchain4j/pull/533
https://github.com/quarkiverse/quarkus-langchain4j/issues/493

Revert "Upgrade to Quarkus Antora 0.0.4 - fix podman issues"

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java

Currently tool parameters are always added as required parameters.
This PR evaluates the required attribute of the P annotation and adds not required parameters as optional parameters to the ToolSpecification.

Evaluate 'required' attribute of @P annotation in tool for optional parameters.

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DefaultCommittableChatMemory.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/template/ChatMessageTemplate.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/template/ChatMessageTemplateExtension.java
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/ai-services.adoc
docs/modules/ROOT/pages/prompt-generation.adoc
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServicesTest.java
model-providers/watsonx/deployment/src/test/java/com/ibm/langchain4j/watsonx/deployment/ChatMemoryPlaceholderTest.java

Make chat memory available to the system message template

---

embedding-stores/redis/deployment/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStoreProcessor.java

In case that somebody tries to use it with a Quarkus snapshot, etc

Make the Quarkus version parsing a bit safer

---

model-providers/ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaProcessor.java
model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaChatLanguageModelModelIdTest.java
model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaChatLanguageModelModelNameTest.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ModelIdConfigFallbackInterceptor.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ModelIdConfigRelocateInterceptor.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ModelIdToModelNameFunction.java
model-providers/ollama/runtime/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceInterceptor

This is done in order to make the property configurable in a similar way as with OpenAI
- Closes: #909

Allow the use of `uarkus.langchain4j.ollama.chat-model.model-name`

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-pgvector.adoc
embedding-stores/pgvector/runtime/src/main/java/io/quarkiverse/langchain4j/pgvector/runtime/PgVectorEmbeddingStoreConfig.java

In the quarkus-langchain4j extension documentation there is :
[quarkus.langchain4j.pgvector.metadata.storage-mode](https://docs.quarkiverse.io/quarkus-langchain4j/dev/pgvector-store.html#quarkus-langchain4j-pgvector_quarkus-langchain4j-pgvector-metadata-storage-mode)
```quote
quarkus.langchain4j.pgvector.metadata.storage-mode
Metadata type:
COLUMN_PER_KEY: for static metadata, when you know in advance the list of metadata fields. In this case, you should also override the quarkus.langchain4j.pgvector.metadata.definition property to define the right columns.
COMBINED_JSON: For dynamic metadata, when you don’t know the list of metadata fields that will be used.
COMBINED_JSONB: Same as JSON, but stored in a binary way. Optimized for query on large dataset. In this case, you should also …
```

doc: fix wrong property name in pgvector documentation

---

embedding-stores/redis/deployment/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStoreProcessor.java
embedding-stores/redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/RedisEmbeddingStore.java
embedding-stores/redis/runtime/src/main/java/io/quarkiverse/langchain4j/redis/runtime/RedisEmbeddingStoreRecorder.java

No longer needed with Quarkus 3.15

Remove the workaround for Redis embedding search

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java

The issue would occur when an AiService contained
multiple methods, one of which did not generate an Image

Fix issue with Image generation in AiService

---

web-search-engines/tavily/runtime/src/main/java/io/quarkiverse/langchain4j/tavily/QuarkusTavilyWebSearchEngine.java
web-search-engines/tavily/runtime/src/main/java/io/quarkiverse/langchain4j/tavily/ShadowSensitiveData.java
web-search-engines/tavily/runtime/src/test/java/io/quarkiverse/langchain4j/tavily/ShadowSensitiveDataTest.java

Fixes the #958 issue. 
There are two design decisions taken here that we might discuss for sure.
The first one is that the class is local to be used by the Tavily module, but it could be located in a "common" module so that any other system can use this feature for passwords. Maybe for now, we can leave it as is,  but it is something we can have in mind.
The second was to figure out whether to use the VertX JSON feature to parse the body or start using some string manipulations. To keep things simple, I decided to use JSON instead of String manipulation utilities. I know this has an impact on performance, but it is INFO logs, so I am not sure if they would be enabled in production. Also, to avoid having potential IndexOutOfBound errors.

Shadows api key from tavily logs

---

model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/AiChatServiceTest.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxUtils.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatMessage.java

This allows the use of models like `llama-3-2-90b-vision-instruct`.

Enable watsonx.ai to process ImageContent in UserMessage

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProviderMetaBuildItem.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/LangChain4jDevUIProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/ToolProviderInfo.java
core/deployment/src/main/resources/dev-ui/qwc-tools.js
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/ToolProviderTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DeclarativeAiServiceCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java
docs/modules/ROOT/pages/agent-and-tools.adoc

In this PR, the idea is to implement the selection of tools dynamically on incoming message
Make ToolProvider from LangChain4J Quarkus ready
We can set our ToolProvider like this:
```JAVA
@RegisterAiService(toolProviderSupplier = MyCustomToolProviderSupplier.class)
interface MyServiceWithToolProvider {
String chat(@UserMessage String msg, @MemoryId Object id);
}
```
Add a simple Supplier like this:
```JAVA
@ApplicationScoped
public class MyCustomToolProviderSupplier implements Supplier<ToolProvider> {
@Inject
MyCustomToolProvider myCustomToolProvider;
@Override
public ToolProvider get() {
return myCustomToolProvider;
}
}
``` 
Now, we can select tools dynamically in our ToolProvider like this:
```Java
@ApplicationScoped
public class MyCustomToolProvider implements ToolProvider {
@Override …
```

[FEATURE] ToolProvider | Select tools dynamically on incoming message

---

model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModel.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaClient.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaEmbeddingModel.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/OllamaRecorder.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/LangChain4jOllamaConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
model-providers/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/common/QuarkusOpenAiClient.java
model-providers/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/common/runtime/AdditionalPropertiesHack.java
model-providers/openai/openai-vanilla/deployment/pom.xml
model-providers/openai/openai-vanilla/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/OpenAiProcessor.java
model-providers/openai/openai-vanilla/deployment/src/test/java/io/quarkiverse/langchain4j/openai/test/OpenAiChatLanguageModelTlsConfigurationTest.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiChatModelBuilderFactory.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiEmbeddingModelBuilderFactory.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiImageModel.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiModerationModelBuilderFactory.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/QuarkusOpenAiStreamingChatModelBuilderFactory.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java
model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/config/LangChain4jOpenAiConfig.java
model-providers/openai/openai-vanilla/runtime/src/main/resources/META-INF/services/dev.langchain4j.model.openai.spi.OpenAiChatModelBuilderFactory
model-providers/openai/openai-vanilla/runtime/src/main/resources/META-INF/services/dev.langchain4j.model.openai.spi.OpenAiEmbeddingModelBuilderFactory
model-providers/openai/openai-vanilla/runtime/src/main/resources/META-INF/services/dev.langchain4j.model.openai.spi.OpenAiModerationModelBuilderFactory
model-providers/openai/openai-vanilla/runtime/src/main/resources/META-INF/services/dev.langchain4j.model.openai.spi.OpenAiStreamingChatModelBuilderFactory
samples/email-a-poem/pom.xml

This allows the TLS configuration name to
be applied like so:
```properties
quarkus.langchain4j.ollama.tls-configuration-name=foo
```
Where it's expected that the user would have also
done something like:
```properties
quarkus.tls.foo.trust-store.jks.path=truststore.jks
quarkus.tls.foo.trust-store.jks.password=pass
```
- Resolves: #993

Add support for TLS configuration name

---

model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatAllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatDefaultPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/GenerationAllPropertiesTest.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/LangChain4jWatsonxConfig.java

This PR fixes an issue that prevented model selection in watsonx.ai when using `chat` mode. Additionally, it introduces support for inheriting `api-key`, `base-url`, `space-id`, and `project-id` properties across different AIServices.
For example, suppose that a developer has two different AiServices, the `application.properties` can be set up as follows:
```properties
quarkus.langchain4j.watsonx.base-url=<url>
quarkus.langchain4j.watsonx.api-key=<api-key>
quarkus.langchain4j.watsonx.project-id=<project-id>
quarkus.langchain4j.watsonx.extractor.log-requests=true
quarkus.langchain4j.watsonx.extractor.chat-model.model-id=ibm/granite-13b-instruct-v2
quarkus.langchain4j.watsonx.rephrase.log-requests=true
quarkus.langchain4j.watsonx.rephrase.chat-model.model-id=meta-llama/llama-3-1-70b-instruct …
```

Fix incorrect model-id parameter in WatsonxRecorder

---

samples/chatbot-web-search/src/main/java/io/quarkiverse/langchain4j/sample/chatbot/Bot.java

This seems to make answering questions like "Give me yesterday's news headlines" more reliable, because otherwise it sometimes uses a query like "news headlines yesterday", but the search engine doesn't understand this concept, so it returns completely random old news (it did that during my recent demo :) ).

Improve web-search sample

---

embedding-stores/neo4j/pom.xml

Without a description, extensions inherit the description of the parent pom:

Add description for neo4j extension

---

rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagConfig.java
rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRagRecorder.java
rag/easy-rag/runtime/src/main/java/io/quarkiverse/langchain4j/easyrag/runtime/EasyRetrievalAugmentor.java

Allowing to specify `minScore` through configuration.
Also a little refactoring to pass the whole `EasyRagConfig` into the `EasyRetrievalAugmentor` rather than just the `maxResults`

Easy-rag: allow to specify minScore through configuration

---

core/deployment/pom.xml
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailPromptTemplateTest.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailPromptTemplateTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrail.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrailParams.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailParams.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java

I need some thoughts to check if I am going in the right direction.
---
This pull request introduces enhancements to the guardrails feature and adds a new test for input validation in the `langchain4j` project. Key changes include adding a new dependency, creating a comprehensive test class, and modifying existing classes to support template parameters in guardrails.
* [`core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrail.java`](diffhunk://#diff-f02c934a84bdd1b3759b7dbbbd749a02c05f688bf1ad7a193b89fea6d2a78357L53-R56): Added `promptTemplate` and `variables` to `InputGuardrailParams` to support template parameters in guardrails.
* [`core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java`](diffhunk://#diff- …

Add prompt template and variables to input / output guardrails

---

core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailChainTest.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/OutputGuardrailOnStreamedResponseValidationTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/GuardrailParams.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/GuardrailResult.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrailParams.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrail.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailParams.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailResult.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java

Implements https://github.com/quarkiverse/quarkus-langchain4j/issues/1020
/cc @gsmet @geoand @lordofthejars

Allow to rewrite LLM result in an OutputGuardrail

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devservice/DevServicesOllamaProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/items/ImplicitlyUserConfiguredChatProviderBuildItem.java
integration-tests/multiple-providers/src/main/resources/application.properties
integration-tests/multiple-providers/src/test/java/org/acme/example/multiple/MultipleChatProvidersTest.java
model-providers/ollama/deployment/src/main/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaProcessor.java

In Ollama (and others in the future) this is possible because
the model-id is a build time property
- Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1055

Allow for Ollama configuration to make `quarkus.langchain4j.foo.chat-model.provider` unnecessary

---

model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java

We also catch `MismatchedInputException` when the
results are being streamed back as it indicates
we are still in an intermediate state
- Fixes: #685

Properly handle Ollama streaming

---

rag/easy-rag/runtime/pom.xml

This cleans up the dependency tree a bit
Fixes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1077

Easy RAG extension: don't depend on the upstream Easy RAG module

---

core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/JsonGuardrailsUtilsTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/JsonGuardrailsUtils.java

The test being in `runtime` breaks the build order, see the recent failures in https://github.com/quarkiverse/quarkus-langchain4j/actions/workflows/build-push.yml
I've moved it to the deployment module and rewritten it from `@QuarkusTest` to the internal framework. I had to make `JsonGuardrailsUtils` public though...

Move JsonGuardrailsUtilsTest to the deployment module

---

core/deployment/src/test/java/io/quarkiverse/langchain4j/test/tools/ToolExecutionModelWithStreamingUnsupportedTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceStreamingResponseHandler.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceTokenStream.java

In this case, instead of swallowing the exception, pass it downstream.

Detect when models to not support tools when using streaming

---

model-providers/jlama/deployment/src/main/java/io/quarkiverse/langchain4j/jlama/deployment/JlamaProcessor.java

If my app has more than one AIService that both use the same model, I get the following error when trying to package my app. This PR fixes this issue.
```shell
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:54 min
[INFO] Finished at: 2024-11-21T14:57:52-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.16.4:build (default) on project insurance-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step …
```

When creating fastJar don't try to include models more than once

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/BeansProcessor.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/QuarkusJsonCodecFactory.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceStreamingResponseHandler.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceTokenStream.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/tool/ToolSpecificationObjectSubstitution.java
docs/modules/ROOT/pages/includes/attributes.adoc
model-providers/anthropic/deployment/src/test/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicChatLanguageModelSmokeTest.java
model-providers/anthropic/deployment/src/test/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicStreamingChatLanguageModelSmokeTest.java
model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/JlamaModel.java
model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/MistralAiRestApi.java
model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/QuarkusMistralAiClient.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/MessageMapper.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/Tool.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatMessage.java
pom.xml

Upgrade to LangChain4j 0.36.2

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/NamedAiServicesAreResolvableByNameTest.java

Enable resolution of AI services by bean name

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java

Previously when a method had a single parameter, the warning was displayed 
- Closes: #1108

Properly warn about missing javac -parameters flag

---

core/deployment/src/test/java/io/quarkiverse/langchain4j/test/guardrails/InputGuardrailRewritingTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/GuardrailResult.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrail.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrailParams.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/InputGuardrailResult.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailResult.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java

This pull request introduces the possibility of rewriting the user messages from the input guardrails. At the moment it is only possible to read and rewrite the complete materialized user message immediately before submitting it to the LLM. I don't know if it would make sense to also allow a rewrite on the single input parameters level (before materializing the complete user message), but if required I'm open to iterate on this and eventually also add this possibility.
/cc @lordofthejars @cescoffier @geoand

Allow rewriting of user messages from input guardrails

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-jlama.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-jlama_quarkus.langchain4j.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java_quarkus.langchain4j.adoc
model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/runtime/config/LangChain4jJlamaFixedRuntimeConfig.java
model-providers/llama3-java/runtime/src/main/java/io/quarkiverse/langchain4j/llama3/runtime/config/LangChain4jLlama3FixedRuntimeConfig.java

Use `user.home` as default for models-path for jlama and llama3 docs
Code is using `user.home`:
* https://github.com/quarkiverse/quarkus-langchain4j/blob/main/model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/JlamaModelRegistry.java#L20
* https://github.com/quarkiverse/quarkus-langchain4j/blob/main/model-providers/llama3-java/runtime/src/main/java/io/quarkiverse/langchain4j/llama3/Llama3ModelRegistry.java#L41
But the config docs default was using `user.name`

Use user.home as default for models-path for jlama and llama3 docs

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/auth/ModelAuthProvider.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaRestApi.java
model-providers/ollama/runtime/src/test/java/io/quarkiverse/langchain4j/ollama/OllamaRestApiFilterTest.java
model-providers/openai/openai-common/runtime/pom.xml
model-providers/openai/openai-common/runtime/src/main/java/io/quarkiverse/langchain4j/openai/common/OpenAiRestApi.java
model-providers/openai/openai-common/runtime/src/test/java/io/quarkiverse/langchain4j/openai/common/OpenAIRestAPIFilterTest.java
model-providers/vertex-ai-gemini/runtime/pom.xml
model-providers/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertxAiGeminiRestApi.java
model-providers/vertex-ai-gemini/runtime/src/test/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertxAiGeminiRestApiTokenFilterTest.java

A typical use case is when the Authorization header is injected by a proxy (sidecar container).
Closes #1128

Support no authorization header being set when null is returned from ModelAuthProvider

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-jlama.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-jlama_quarkus.langchain4j.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java_quarkus.langchain4j.adoc
docs/modules/ROOT/pages/jlama.adoc
docs/modules/ROOT/pages/llama3.adoc
model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/JlamaModelRegistry.java
model-providers/jlama/runtime/src/main/java/io/quarkiverse/langchain4j/jlama/runtime/config/LangChain4jJlamaFixedRuntimeConfig.java
model-providers/llama3-java/runtime/src/main/java/io/quarkiverse/langchain4j/llama3/Llama3ModelRegistry.java
model-providers/llama3-java/runtime/src/main/java/io/quarkiverse/langchain4j/llama3/runtime/config/LangChain4jLlama3FixedRuntimeConfig.java

Store local models under `~/.langchain4j/models`
Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1133
Location of cached models changes from `${user.home}/.jlama/models` and `${user.home}/.llama3java/models` to single `${user.home}/.langchain4j/models`.
Current `quarkus-langchain4j-jlama` and `quarkus-langchain4j-llama3-java` users can rename the old directory to `${user.home}/.langchain4j` to avoid new downloads of the models after upgrade.
I have included some minor changes in this PR (separate commits) related to jlama and llama3:
* Include Llama3.java in navigation
* Hint about models-path property in jlama and llama3 docs

Store local models under `~/.langchain4j/models`

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-llama3-java_quarkus.langchain4j.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-openai_quarkus.langchain4j.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-tavily.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-tavily_quarkus.langchain4j.adoc
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/DeclarativeAiServicesTest.java

Fix named AiService handling

---

model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaJsonOutputTest.java
model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaStructuredOutputTest.java
model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaTextOutputTest.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ChatRequest.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/FormatJsonSerializer.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModel.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/runtime/config/ChatModelConfig.java

This PR enables the use of structured output with json_schema in Ollama.
My idea is to force the use of the structured output + json_schema every time an AIService returns a POJO and the developer doesn't fill the "format" property. In this second case, the value chosen by the developer will have the priority.

Add support for structured output in Ollama

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/streaming/BlockingMemoryStoreOnStreamedResponseTest.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/streaming/StreamTestUtils.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceStreamingResponseHandler.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceTokenStream.java

Fix https://github.com/quarkiverse/quarkus-langchain4j/issues/1120
This commit addresses issues with using the blocking memory store in streamed responses.
* Ensures the execution captures whether the caller is running on a worker thread.
* Switches to worker threads for every emission and completion event when the caller is using a worker thread.
* Relies on executeBlocking to propagate the context automatically when possible.
Note:
* The blocking memory store cannot be used when invoked on the event loop. It now requires that the caller must be on a worker thread.

Fix Blocking Memory Store Usage in Streamed Mode

---

core/deployment/pom.xml
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DeclarativeAiServiceBuildItem.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DotNames.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/LangChain4jDevUIProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/items/ToolQualifierProvider.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/DeclarativeAiServiceCreateInfo.java
model-providers/openai/openai-vanilla/deployment/pom.xml
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/RestClientToolTest.java
samples/pom.xml
samples/weather-agent/README.md
samples/weather-agent/pom.xml
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/CityExtractorAgent.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/WeatherForecastAgent.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/WeatherResource.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/geo/GeoCodingService.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/geo/GeoResult.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/geo/GeoResults.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/weather/Daily.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/weather/DailyUnits.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/weather/DailyWeatherData.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/weather/WeatherForecast.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/weather/WeatherForecastService.java
samples/weather-agent/src/main/java/io/quarkiverse/langchain4j/weather/agent/weather/WmoCode.java
samples/weather-agent/src/main/resources/application.properties

This makes it a lot easier to create Agentic AI systems (an example of which is added to the samples)

Allow Rest Client and AI Service to be used as tools

---

model-providers/openai/azure-openai/deployment/src/main/java/io/quarkiverse/langchain4j/azure/openai/deployment/AzureOpenAiProcessor.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
model-providers/openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/DisabledModelsAzureOpenAiRecorderTest.java

Fixes #1155.
@geoand I've updated it the same way we did checks for `ChatModel` and `StreamingChatModel`.
I've confirmed that with this PR, after deploying `text-embedding-ada-002` in my Azure OpenAI account, with the `secure-poem-multiple-providers` demo, that if I add
```
quarkus.langchain4j.openai.embedding-model.provider=azure-openai
quarkus.langchain4j.azure-openai.embedding-model.resource-name=quarkus-langchain4j
#default deployment name
quarkus.langchain4j.azure-openai.embedding-model.deployment-name=text-embedding-ada-002
quarkus.langchain4j.azure-openai.embedding-model.log-requests=true
quarkus.langchain4j.azure-openai.embedding-model.log-responses=true
``` 
and have `EmbeddingModel` injected and the Azure OpenAI related method updated to
```
@GET
@Path("azure-openai")
public …
```

Update Azure OpenAI to check ModelAuthProvider during Embedding and Image model creation

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/LangChain4jDotNames.java
core/deployment/src/test/java/io/quarkiverse/langchain4j/test/ToolProviderTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java

This makes tool provider autowiring work the same as for retrieval augmentors, audit service, moderation model...
Prerequisite for https://github.com/quarkiverse/quarkus-langchain4j/issues/1146 (draft PR coming soon)

Fix BeanIfExistsToolProviderSupplier, introduce NoToolProviderSupplier

---

model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/runtime/MistralAiRecorder.java
model-providers/mistral/runtime/src/main/java/io/quarkiverse/langchain4j/mistralai/runtime/config/LangChain4jMistralAiConfig.java

This fixes an issue I encountered where Mistral AI requires apiKey even when setting a custom baseUrl.

Don't require api key when using custom base url for mistralai

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/JandexUtil.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/EmbeddingStoreJsonRPCService.java
samples/email-a-poem/README.md
samples/secure-fraud-detection/README.md
samples/secure-poem-multiple-models/README.md
samples/secure-sql-chatbot/README.md

* Typo fixes in JandexUtil and EmbeddingStoreJsonRPCService
* Typo fixes in samples
for login vs. log in I followed explanation from https://www.reddit.com/r/webdev/comments/aml4hb/login_vs_log_in_are_we_using_these_wrong/

Typo fixes in samples and JandexUtil + EmbeddingStoreJsonRPCService from core

---

.gitignore
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorder.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ChatModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/EmbeddingModelConfig.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/runtime/config/ImageModelConfig.java
model-providers/openai/azure-openai/runtime/src/test/java/io/quarkiverse/langchain4j/azure/openai/runtime/AzureOpenAiRecorderEndpointTests.java

For chat, embedding, and image-model: api-key, ad-token, api-version
- Closes: #1154

Add keys to override config for chat, embedding and image-model for Azure OpenAI

---

testing/core/src/main/java/io/quarkiverse/langchain4j/guardrails/OutputGuardrailResultAssert.java

the `OutputGuardrailResultAssert.isSuccessful` isn't properly checking for success. This fixes it.

Fix isSuccessful

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java

Enhance the message shown to the user when output guardrails fail. If the user has multiple guardrails the current message doesn't at all indicate which guardrail failed. This is what they see:
```
io.quarkiverse.langchain4j.runtime.aiservice.GuardrailException: Output validation failed. The guardrails have reached the maximum number of retries
at io.quarkiverse.langchain4j.runtime.aiservice.GuardrailsSupport.invokeOutputGuardrails(GuardrailsSupport.java:109)
at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:420)
at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:138)
at …
```

Enhance output message when output guardrails fail

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java

Output guardrails should support structured output.
I did a little refactoring so that the code path for executing a chat request all funnels through the same set of code, that way the guardrails re-use what's in `AiServiceMethodImplementationSupport`.
Fixes #1200

Output guardrails should support structured output

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/guardrails/AbstractJsonExtractorOutputGuardrail.java

Allow customization of invalid json reprompt.
In some implementations I'm finding that the message `Make sure you return a valid JSON object following the specified format` is too generic. On specific implementations I'd like to include the json format in the reprompt message.
This change allows implementors to override the message, or change the implementation of the reprompt altogether (maybe an implementor just wants to fail?).
This change is 100% backwards compatible with current behavior but allows implementors to customize.

Allow customization of invalid json reprompt

---

testing/scorer/scorer-core/src/main/java/io/quarkiverse/langchain4j/testing/scorer/EvaluationReport.java
testing/scorer/scorer-core/src/main/java/io/quarkiverse/langchain4j/testing/scorer/Scorer.java
testing/scorer/scorer-core/src/test/java/io/quarkiverse/langchain4j/testing/scorer/ScorerTest.java

as discussed https://github.com/quarkiverse/quarkus-langchain4j/pull/1209/files#r1908303398
this change provides 
* stable order for `scorer.evaluate(...)`
* generic typed `EvaluationReport<T> report = scorer.evaluate(...);`
@cescoffier or is it by purpose that `EvaluationReport` was not generically typed? i stumbled upon it having some compile-issues when sorting

Provide Evaluations in same order as they where submitted

---

model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/AiEmbeddingTest.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxEmbeddingModel.java

Handle API request limits in WatsonxEmbeddingModel

---

docs/modules/ROOT/pages/jlama.adoc

Fixes Jlama docs setting the correct properties name.

Fixes Jlama docs

---

model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaStreamingChatLanguageModel.java

The input and output token count in OllamaStreamingChatLanguageModel seems to be switched.

Fix switched input/output token usage in ollama streaming

---

model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaChatLanguageModelToolTest.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/OllamaChatLanguageModel.java

Not sure why I needed to add the quarkus-junit5 dependency for my test to run.
Added behavior to filter out hallucinated toolExecutionRequests.
Had to add some reflection to write a test with mocked client in OllamaChatLanguageModel. I am happy about suggestions.
Also I am not happy with the assertions in the test "doesNotCrashIfToolNotPresent". But I did not find out how to get the content of the messagebuilder from "chatResponseWithHalucinatedTool" to be present in the resultin ChatResponse. I think it has something todo with missing ToolExecutors but added breakpoints into the ToolExecutors present in the repo did not help since they didn't hit.
Fixes #1232 (hallucinated toolExecutionRequests)

Handle hallucinated tool execution requests

---

core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
embedding-stores/neo4j/runtime/src/main/resources/META-INF/quarkus-extension.yaml
embedding-stores/pgvector/runtime/src/main/resources/META-INF/quarkus-extension.yaml
model-providers/watsonx/runtime/src/main/resources/META-INF/quarkus-extension.yaml

* quarkus-extension.yaml for Neo4j embedding store
* Sync extensions naming (Watsonx, pgvector, core)
* Sync extensions status (Watsonx, pgvector)
`quarkus extension list --installable --category ai` command:
Watsonx and pgvector extensions have `status: "preview"`, all the other extensions have `status: "experimental"`
* see https://code.quarkus.io/?extension-search=quarkus-langchain4j

Extensions descriptors updates

---

model-providers/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/ContentMapper.java
samples/secure-poem-multiple-models/src/main/java/io/quarkiverse/langchain4j/sample/PoemResource.java

Gemini may request multiple function calls, for example:
```
{
"candidates": [
{
"content": {
"role": "model",
"parts": [
{
"functionCall": {
"name": "getLoggedInUserName",
"args": {}
}
},
{
"functionCall": {
"name": "getPreferredJavaFeature",
"args": {}
}
}
]
},
"finishReason": "STOP"
]
```
Currently, on `main`, Vertex AI Gemini model provider does not include all function calls, so after fixing that I got a nearly correct response:
```
{"contents":[
{"role":"user","parts":[{"text":"Write a short 1 paragraph poem about a Java programming language feature preferred by the user.\nSet an author name to the model or deployment name which created the poem.\nPlease start by greeting the currently logged in user and asking to enjoy reading the poem, address this user by name."}]}, …
```

Get all Gemini function calls included and paired with matching function responses

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/template/ChatMessageTemplateExtension.java
model-providers/ollama/deployment/src/test/java/io/quarkiverse/langchain4j/ollama/deployment/OllamaCustomMessageTest.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/ChatResponse.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/Message.java
model-providers/ollama/runtime/src/main/java/io/quarkiverse/langchain4j/ollama/MessageMapper.java

Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1248
Note that I've submitted this as a draft PR because this depends on the next LangChain4j release that adds the ability to specify a generic custom message type and makes it possible to use custom messages with Ollama (see https://github.com/langchain4j/langchain4j/pull/2399).

Make it possible to use a LangChain4j CustomMessage with Ollama

---

docs/modules/ROOT/pages/testing.adoc

I've fixed a small typo related to sample files.
The correct way to declare a sample is to use `expected-output` not `expectedOutput` :   
```yaml
- name: Sample1
parameters:
- "parameter1"
expected-output: "expected1"
tags: ["tag1"]
```

Fix testing doc typo

---

core/opentelemetry-tests/src/test/java/io/quarkiverse/langchain4j/opentelemetry/test/ListenersProcessorAbstractSpanChatModelListenerTest.java
core/opentelemetry-tests/src/test/java/io/quarkiverse/langchain4j/opentelemetry/test/ListenersProcessorTwoChatModelSpanContributorsTest.java
pom.xml

This is needed to make the tests work with
both the latest Quarkus LTS and Quarkus Main

Don't depend on internal OTel types in tests

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServiceAsToolBoxTest.java
model-providers/openai/openai-vanilla/deployment/src/test/java/org/acme/examples/aiservices/AiServiceAsToolTest.java

Fixes bug discussed here https://github.com/mariofusco/quarkus-agentic-ai/commit/0516a93f1313ee78a1609c5d96b476d5ebba8991#commitcomment-152919896
Adding the AI service tool among the unremoveable beans using its class name is wrong because that actual bean that shouldn't be removed is the generated one that implements the AI service but has a different class name. Conversely, registering its bean type using its class fixes the problem.
/cc @geoand

Fix AI services as tools lookup using @ToolBox annotation

---

model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/AiChatCacheTokenTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/AiGenerationCacheTokenTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatAllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatDefaultPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/GenerationAllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/GenerationDefaultPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/HttpErrorTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ResponseSchemaOnTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/WireMockAbstract.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/WireMockUtil.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxGenerationModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxUtils.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java

With the beta2 release of langchain4j the `generate` method in the `ChatLanguageModel` and `StreamingChatLanguageModel` interfaces will no longer be available. I have updated the tests in the watsonx.ai module to be ready for the new release.

Update watsonx.ai test classes

---

model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiChatLanguageModel.java
model-providers/google/gemini/ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/ai/runtime/gemini/AiGeminiEmbeddingModel.java
model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GeminiChatLanguageModel.java
model-providers/google/gemini/gemini-common/runtime/src/main/java/io/quarkiverse/langchain4j/gemini/common/GeminiEmbeddingModel.java
model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiChatLanguageModel.java
model-providers/google/vertex-ai-gemini/runtime/src/main/java/io/quarkiverse/langchain4j/vertexai/runtime/gemini/VertexAiGeminiEmbeddingModel.java

This PR attempts to minimize the duplication between AiGemini and VertexAiGemini by pushing the common `ChatModel` and `EmbeddingModel` code down to the `gemini-common` module.
Some duplication will still remain and can be minimized during some follow-up iterations but, hopefully, with the `ChatModel` and `EmbeddingModel` code becoming shared, it will be much easier to deal with fixing the model or content related issues for both providers at the same time.
CC @geoand @lordofthejars

Create common Gemini ChatModel and EmbeddingModel code

---

mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/config/McpClientConfig.java

Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1346

Make stdio the default MCP transport

---

codestarts/chatbot/runtime/pom.xml
codestarts/chatbot/runtime/src/main/codestarts/quarkus/langchain4j-chatbot-codestart/base/src/main/resources/META-INF/resources/index.html
samples/chatbot-easy-rag/pom.xml
samples/chatbot-easy-rag/src/main/resources/META-INF/resources/index.html
samples/chatbot-web-search/pom.xml
samples/chatbot-web-search/src/main/resources/META-INF/resources/index.html
samples/chatbot/pom.xml
samples/chatbot/src/main/resources/META-INF/resources/index.html
samples/mcp-sse-client-server/mcp-client/pom.xml
samples/mcp-sse-client-server/mcp-client/src/main/resources/META-INF/resources/index.html
samples/mcp-tools/pom.xml
samples/mcp-tools/src/main/resources/META-INF/resources/index.html
samples/secure-sql-chatbot/pom.xml
samples/secure-sql-chatbot/src/main/resources/templates/movieMuse.html
samples/sql-chatbot/pom.xml
samples/sql-chatbot/src/main/resources/META-INF/resources/index.html

Bump wc-chatbot from 0.2.0 to 0.2.1 and increase wc-chatbot window size
Window size is adjustable since https://github.com/yishiashia/wc-chatbot/pull/7
Changing from the default 360 x 500 to 500 x 600 px to have more space for the interaction and returned content.

Bump wc-chatbot from 0.2.0 to 0.2.1 and increase wc-chatbot window size

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/devui/ChatJsonRPCService.java

Fixes https://github.com/quarkiverse/quarkus-langchain4j/issues/1359 (the problem was that a REST client gets a  `@RestClient` qualifier and we look up without specifying any qualifiers)
This is not optimal, but we don't know what qualifiers the beans with tools might have, so let's try to just inject `any` bean...

Use the Any qualifier when injecting tools for the Dev UI

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/LangChain4jDevUIProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/devui/OpenWebUIDevUIProcessor.java
model-providers/openai/openai-vanilla/deployment/src/main/java/io/quarkiverse/langchain4j/openai/deployment/devui/OpenAiDevUIProcessor.java

This is due to an upcoming change in Execution Model Validation [1] where we need the `JsonRPCProvidersBuildItem` produced always, not only in dev mode. JSON RPC providers can use execution model affecting annotations, so we need to know about them, otherwise a non-dev build would fail with an incorrect validation error.
[1] https://github.com/quarkusio/quarkus/pull/46965

Dev UI: always produce JsonRPCProvidersBuildItem

---

docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-mcp_quarkus.langchain4j.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-milvus.adoc
docs/modules/ROOT/pages/includes/quarkus-langchain4j-milvus_quarkus.langchain4j.adoc
model-providers/bedrock/runtime/src/main/java/io/quarkiverse/langchain4j/bedrock/runtime/jaxrsclient/JaxRsSdkHttpClientExecutable.java

This is done because `WebClientApplicationException`
that was used before has since been removed
from Quarkus `main`

Use ClientWebApplicationException in Bedrock

---

core/deployment/src/test/java/io/quarkiverse/langchain4j/test/toolresolution/ExplicitToolBoxAndProviderSupplierTest.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/RegisterAiService.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/AiServicesRecorder.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java

This change follows a [similar improvement](https://github.com/langchain4j/langchain4j/pull/2819), made on LangChain4j, intended to allow an AI service to use both statically defined and dynamically loaded tools (possibly from one or more MCP servers) at the same time. 
/cc @jmartisk @geoand

Allow to mix static and dynamic tools

---

model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/AiChatServiceTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatAllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ToolChoiceTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/WireMockUtil.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxStreamingChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatMessage.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatParameters.java

This commit avoids an infinite loop when a developer uses the `tool-choice` option.  The fix is for the `watsonx.ai` module, but maybe this can also affect other models in `quarkus-langchain4j` and could be something to move in the core part.
I've done a quick fix in `watsonx.ai` because I'm working on a project and I need to use the `tool-choice` in the next few days.
Let's understand if this is something that can be moved to the core or if it is a problem specific to the watsonx.ai module.

Prevent infinite loop when using tool-choice in watsonx.ai

---

model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ChatAllPropertiesTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ToolChoiceNameTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ToolChoiceNameToolNotFoundTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/ToolChoiceToolNotFoundTest.java
model-providers/watsonx/deployment/src/test/java/io/quarkiverse/langchain4j/watsonx/deployment/WireMockUtil.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/WatsonxChatModel.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/bean/TextChatParameters.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/WatsonxRecorder.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ChatModelConfig.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/EmbeddingModelConfig.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/GenerationModelConfig.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/LangChain4jWatsonxConfig.java
model-providers/watsonx/runtime/src/main/java/io/quarkiverse/langchain4j/watsonx/runtime/config/ScoringModelConfig.java

This commit updates default configurations:
- **chat-model.model-id** from `mistralai/mistral-large` to `meta-llama/llama-4-maverick-17b-128e-instruct-fp8`
- **embedding-model.model-id** from `ibm/slate-125m-english-rtrvr` to `ibm/granite-embedding-278m-multilingual`
- **api version** from `2024-03-14` to `2025-04-23`
It also adds support for:
- Tool invocation control via `tool-choice` (auto or required) and `tool-choice-name` (forces a specific tool, overriding `tool-choice`)
- Inheritable fields: `timeout`, `log-requests`, and `log-responses`

Update watsonx.ai defaults and add tool choice configuration

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodCreateInfo.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusToolProviderRequest.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/AbstractMockHttpMcpServer.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpClaudeConfigTest.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpClientAndToolProviderCDITest.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpHealthCheckTest.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/McpOverHttpTransportTest.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/Mock2HttpMcpServer.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/Mock3HttpMcpServer.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/MockHttpMcpServer.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/MultipleMcpClientsTest.java
mcp/deployment/src/test/java/io/quarkiverse/langchain4j/mcp/test/NoAutomaticToolProviderTest.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpToolBox.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/QuarkusMcpToolProvider.java

This is an implementation for https://github.com/quarkiverse/quarkus-langchain4j/issues/1409
At the moment the `McpToolBox` annotation is only used to limit the MCP servers that a AI service can use. In other words if you have configured the MCP servers A, B and C, the following service:
```
@RegisterAiService
public interface MyService {
@McpToolBox({"A", "C"})
String chat(String query);
}
```
will be provided only for tools in the server A and C, but not B. If the `McpToolBox` annotation is present with no values or is not present at all it will behave in the same way, automatically providing all the tools for all the configured MCP servers. I did this to keep backward compatibility, but in reality what I would like to do is giving access to the MCP provided tools only to method …

Add fine-grained control for MCP server(s) provided tools

---

mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpProcessor.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpClientHealthCheck.java

This is needed to avoid warnings at both build time and runtime which stemmed from the fact that the
health check was previously always a bean.
The build time warnings were like:
```
2025-05-12 16:07:09,173 WARN  [io.qua.arc.pro.BeanArchives] (build-40) Failed to index org.eclipse.microprofile.health.HealthCheck: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for quarkus-langchain4j-sample-mcp-client-1.0-SNAPSHOT@5be49b60
2025-05-12 16:07:50,576 INFO  [io.qua.arc.pro.IndexClassLookupUtils] (build-40) Class for name: org.eclipse.microprofile.health.HealthCheck was not found in Jandex index. Please ensure the class is part of the index.
```
and the runtime ones:
```
2025-05-12 16:07:51,180 WARN  [io.qua.arc.ComponentsProvider] (Quarkus Main Thread) …
```

Make MCP Client Health check actually optional

---

README.md

DeepWiki will update the [repo wiki](https://deepwiki.com/quarkiverse/quarkus-langchain4j) weekly if it sees a badge in the readme file.

Add DeepWiki badge to readme

---

samples/chatbot-easy-rag-kotlin/src/main/resources/META-INF/resources/components/demo-title.js
samples/chatbot-easy-rag-kotlin/src/main/resources/META-INF/resources/index.html

Make it look better on demo screen
- Adjust demo-title explanation width to 90%
- Dropped `height: 100vh` and `overflow: hidden` to fix scrolling
- Increase text size in chat-bubble

Improve styles in Kotlin sample

---

samples/mcp-sse-client-server/mcp-client/src/main/resources/application.properties

- `quarkus.langchain4j.mcp.generate-tool-provider.*` (naming a MCP client `generate-tool-provider`) is confusing  because it "clashes" with the property `quarkus.langchain4j.mcp.generate-tool-provider` that is not tied to any particular client
- `@McpToolBox` annotation without a value is only bloating the code and doesn't change anything

Polish the secure-mcp-sse-client-server a bit

---

mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/QuarkusMcpToolProvider.java

Avoid NPE for methods without @McpToolBox

---

.sdkmanrc

.sdkmanrc still points to old JDK 17 - this updates to current JDK 17

Update to current Temurin 17 in .sdkmanrc

---

samples/chatbot-easy-rag-kotlin/pom.xml
samples/chatbot-easy-rag-kotlin/src/main/resources/application-dev.properties
samples/chatbot-easy-rag-kotlin/src/main/resources/application.properties

- Disable `default-kapt` and `default-test-kapt` executions in kotlin-maven-plugin.
- Enable Kotlin incremental compilation
- Upgrade Quarkus Platform to 3.22.3
- Upgrade ai-mocks-openai to 0.4.0
- Remove traces of maven-compiler-plugin
- Upgrade jandex-maven-plugin
- Add opentelemetry dependency
- Use new embedding model `text-embedding-3-small`

Kotlin sample: Optimizations

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/listeners/MetricsChatModelListener.java

When using Azure OpenAI there is no model name so we get in the logs the following error:
>     2025-05-28 07:41:30,789 WARN [io.qua.lan.azu.ope.AzureOpenAiChatModel] (executor-thread-1) 52093f841912115693757cf41ecec505 Exception while calling model listener: java.lang.NullPointerException
>     at java.base/java.util.Objects.requireNonNull(Objects.java:233)
>     at io.micrometer.core.instrument.ImmutableTag.(ImmutableTag.java:37)
>     at io.micrometer.core.instrument.Tag.of(Tag.java:31)
>     at io.micrometer.core.instrument.Tags.of(Tags.java:349)
>     at io.quarkiverse.langchain4j.runtime.listeners.MetricsChatModelListener.onResponse(MetricsChatModelListener.java:79)
>     at io.quarkiverse.langchain4j.azure.openai.AzureOpenAiChatModel.lambda$doChat$2(AzureOpenAiChatModel.java:182)
> …

Fix NPE in MetricsChatModelListener.java

---

codestarts/chatbot/pom.xml

At the moment the codestart looks silly on http://quarkus.io/extensions and http://code.quarkus.io:
Even with the description, though, I'm a bit confused by this extension. We don't normally create standalone extensions for our codestarts, because the idea is that they'd just be hooked into code.quarkus.io. The other langchain4j codestarts aren't published as extensions (you can see at https://quarkus.io/extensions/?search-regex=codestart this the chatbot codestart is the only codestart published that way). 
I guess maybe we've done it that way because, unlike the EasyRAG codestart, it's a cross-extension codestart? It feels like it's maybe mixing concepts from samples and codestarts, though.

Add description to codestart to avoid inheriting parent description

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/ToolProcessor.java

When this happens it's likely an omission on the developer's
part, so let's provide an actionable warning about it

Provide warning when WebSearchTool is used with the proper extension

---

mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/McpProcessor.java
mcp/runtime/pom.xml
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/McpRecorder.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/QuarkusMcpToolProvider.java

When using our weather sample with OTel dependencies, Quarkus LangChain4j now produces the following:
- Closes: #1416

Produce spans for MCP tool calls

---

model-providers/openai/azure-openai/deployment/pom.xml
model-providers/openai/azure-openai/deployment/src/test/java/io/quarkiverse/langchain4j/azure/openai/test/AzureOpenAiStreamingChatModelTest.java
model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java

Fixes exception: Cannot set both 'metadata' and 'finishReason' on ChatResponse.
See also changes from 3c8fc311a277d6a703e763995191e6e598d151f2.

Port changes to construct ChatResponse from AzureOpenAiChatModel to AzureOpenAiStreamingChatModel and add test for AzureOpenAiStreamingChatModel.

---

mcp/deployment/src/main/java/io/quarkiverse/langchain4j/mcp/deployment/devui/McpDevUiProcessor.java
mcp/deployment/src/main/resources/dev-ui/qwc-mcp-clients.js
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/devui/McpClientsJsonRpcService.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/devui/json/JsonSchemaToExampleStringHelper.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/devui/json/McpClientInfo.java
mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/devui/json/McpToolInfo.java

Allows the user to list available tools from all configured MCP clients and execute them from the Dev UI. I attempted to automatically provide an appropriate JSON document that captures the arguments of the tool that is being invoked (but of course, the user will have to change the actual values...).
Video sample that uses the `samples/mcp-tools` sample from this repo:
[simplescreenrecorder-2025-07-08_15.16.54.webm](https://github.com/user-attachments/assets/7da2109a-62f4-496a-ab94-f6d6c4ccda12)

Dev UI page for MCP clients

---

docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/quickstart-rag.adoc
docs/templates/includes/attributes.adoc
pom.xml

Version 1.1.0.CR1 is currently not available in the repository.

Update quickstart-rag.adoc fixing the dependency to langchain4j-embeddings

---

mcp-auth-providers/oidc-mcp-auth-provider/runtime/src/main/java/io/quarkiverse/langchain4j/oidc/mcp/runtime/OidcMcpAuthProvider.java

Fixes #1641
This PR makes sure that the OIDC McpClientAuthFilter only does the work if the request context is active, making sure it does not interfere with various MCP protocol specific actions that have no active request context, when activating it on the fly would not work in any case as the new context would have no token.
@KaiSuchomel Can you please verify this PR ?
Note, this PR fixes the  OIDC McpClientAuthFilter reporting ContextNotActiveException. I'm still seeing MCP server auto-ping not working but I think this is no longer the OIDC McpClientAuthFilter's fault.
If it is the case, let's resolve #1641 and please open another issue, once this PR is approved/merged

Update OidcMcpAuthProvider to ignore requests without active request context

---

core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/QuarkusAiServiceStreamingResponseHandler.java

Disable the ordered execution of blocking actions as it causes a deadlock when the tool itself also requires running on the a blocking action on vertx context.
- Fixes: #1655

Disable the ordered execution of blocking actions

---

mcp/runtime/src/main/java/io/quarkiverse/langchain4j/mcp/runtime/http/QuarkusStreamableHttpMcpTransport.java

Fixed the MCP Streamable Parsing Incomplete response, using record parser.
- Fixes: #1653

added Record Parser to parse each sse event

---

core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/AiServicesProcessor.java
core/deployment/src/main/java/io/quarkiverse/langchain4j/deployment/DotNames.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/AiServiceMethodImplementationSupport.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/ChatEvent.java
core/runtime/src/main/java/io/quarkiverse/langchain4j/runtime/aiservice/GuardrailsSupport.java
docs/modules/ROOT/pages/guide-streamed-responses.adoc

Allow returning a ChatResponse Multi in streaming mode
Otherwise wecan't get the metadata and token usage and associate it with a specific request.
Prevent duplicate final message when using Multi<String> return value
Allow using a new ChatEvent producing multi so consumer can get a stream of all chat events.
relates to #828

Allow returning a ChatResponse Multi in streaming mode

---

model-providers/openai/azure-openai/runtime/src/main/java/io/quarkiverse/langchain4j/azure/openai/AzureOpenAiStreamingChatModel.java

Fixes a NullPointerException that occurs in `AzureOpenAiStreamingChatModel` when Azure OpenAI sends streaming chunks without delta content.
Azure OpenAI streaming responses sometimes include chunks without a delta field. The current code assumes delta is always present, causing NPE at line 237: Cannot invoke "dev.langchain4j.model.openai.internal.chat.Delta.content()" because "delta" is null
Added null check for `delta` object before accessing its content
Tested with streaming requests that previously crashed

Prevent NPE when delta is null in Azure OpenAI streaming

---

rag/easy-rag/runtime/src/main/resources/META-INF/quarkus-extension.yaml

I was a bit disappointed when I followed the guide link for easy rag and it just took me to the top level langchain4j docs. When we have the option and there's an obvious page, should we deep link instead?

Use deep link for easy rag docs

---

model-providers/anthropic/runtime/src/main/java/io/quarkiverse/langchain4j/anthropic/QuarkusAnthropicClient.java

Adding tool_use check to the various message handlers, following the existing implementation in the core LangChain4j library.
Decided to add in passing through the returnThinking boolean config option and also to handle returning the thinking streams as well after comparing the core library.
- Closes: https://github.com/quarkiverse/quarkus-langchain4j/issues/1778

Anthropic handle tool calls

---

model-providers/ollama/runtime/src/main/resources/META-INF/quarkus-extension.yaml

The current link just links to the top level and makes users search.

Use more precise guide link for Ollama

---

model-providers/anthropic/deployment/src/main/java/io/quarkiverse/langchain4j/anthropic/deployment/AnthropicProcessor.java
model-providers/anthropic/runtime/src/main/java/io/quarkiverse/langchain4j/anthropic/runtime/AnthropicRecorder.java

Looking to emit otel span when using anthropic model and noticed they were missing the `gen_ai` attributes.
Digging through the code base, realise the recorder doesn't have the chat model listener
In this pull request, based on the [OpenAIRecorder class](https://github.com/quarkiverse/quarkus-langchain4j/blob/main/model-providers/openai/openai-vanilla/runtime/src/main/java/io/quarkiverse/langchain4j/openai/runtime/OpenAiRecorder.java), add related logic to setup the listener.

enhance: allow anthropic recorder to add chat model listener
